"""Write MATLAB scripts that build the approximate Simulink model."""

from __future__ import annotations

from pathlib import Path
import logging

from .ir import BlockIR, ModelIR

LOGGER = logging.getLogger(__name__)


class MatlabWriter:
    LIBRARY_BLOCKS = {
        "Inport": "simulink/Sources/In1",
        "Outport": "simulink/Sinks/Out1",
        "Constant": "simulink/Sources/Constant",
        "Gain": "simulink/Math Operations/Gain",
        "Sum": "simulink/Math Operations/Sum",
        "Product": "simulink/Math Operations/Product",
        "Saturation": "simulink/Discontinuities/Saturation",
        "Step": "simulink/Sources/Step",
        "Switch": "simulink/Signal Routing/Switch",
        "Integrator": "simulink/Continuous/Integrator",
        "Discrete-Time Integrator": "simulink/Discrete/Discrete-Time Integrator",
        "Unit Delay": "simulink/Discrete/Unit Delay",
        "PassThrough": "simulink/Signal Attributes/Signal Conversion",
        "MATLAB Function": "simulink/User-Defined Functions/MATLAB Function",
    }

    PARAM_MAP = {
        "Port": "Port",
        "Gain": "Gain",
        "Inputs": "Inputs",
        "Value": "Value",
        "UpperLimit": "UpperLimit",
        "LowerLimit": "LowerLimit",
        "Time": "Time",
        "Before": "Before",
        "After": "After",
        "InitialCondition": "InitialCondition",
    }

    def write(self, ir: ModelIR, output_path: Path) -> None:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        text = self.render(ir)
        output_path.write_text(text, encoding="utf-8")
        LOGGER.info("Wrote MATLAB builder script: %s", output_path)

    def render(self, ir: ModelIR) -> str:
        lines: list[str] = []
        lines.extend(self._header(ir))
        lines.extend(self._model_creation(ir))
        lines.append("% Add blocks. Inferred helper blocks include the word inferred in the name.")
        for block in sorted(ir.blocks, key=lambda item: item.execution_index):
            lines.extend(self._render_block(block))
        lines.append("")
        lines.append("% Connect inferred signal dependencies.")
        lines.append("fprintf('[connection] Creating %d signal lines with autorouting.\\n', expectedLineCount);")
        for conn in ir.connections:
            lines.append(
                "try"
            )
            lines.append(
                "    add_line(model, "
                f"{self._mstring(conn.src + '/1')}, "
                f"{self._mstring(conn.dst + '/' + str(conn.dst_port))}, "
                "'autorouting', 'on');"
            )
            lines.append("catch ME")
            lines.append(
                "    warning('Could not add line %s -> %s: %s', "
                f"{self._mstring(conn.src)}, {self._mstring(conn.dst)}, ME.message);"
            )
            lines.append("end")
        lines.append("")
        lines.extend(self._render_validation())
        lines.extend(self._render_annotations(ir))
        lines.append("fprintf('[save] Saving model to %s.slx.\\n', model);")
        lines.append("save_system(model);")
        lines.append(
            "fprintf('[summary] Blocks: %d; signal lines: %d; model: %s; layout: %s.\\n', "
            "actualBlockCount, actualLineCount, model, layoutStrategy);"
        )
        lines.append("")
        return "\n".join(lines)

    def _header(self, ir: ModelIR) -> list[str]:
        original = ir.original_model_name or "unknown"
        layout_strategy = ir.metadata.get("layout_strategy", "Left-to-right signal flow")
        layout_description = ir.metadata.get(
            "layout_description",
            "Blocks are arranged by dependency depth from sources to outputs.",
        )
        return [
            "% Auto-generated by the Python Simulink C reconstruction tool.",
            "% The result is an approximate visualization and starting point.",
            "% Generated from Simulink Coder C, which is not a lossless model format.",
            f"% Original model inferred from C: {original}",
            f"% Layout strategy: {layout_strategy}.",
            f"% Layout note: {layout_description}",
            "% Inferred facts are represented as blocks, lines, and annotations.",
            "",
        ]

    def _model_creation(self, ir: ModelIR) -> list[str]:
        model = self._mstring(ir.model_name)
        original = self._mstring(ir.original_model_name or "unknown")
        layout_strategy = self._mstring(
            ir.metadata.get("layout_strategy", "Left-to-right signal flow")
        )
        layout_description = self._mstring(
            ir.metadata.get(
                "layout_description",
                "Blocks are arranged by dependency depth from sources to outputs.",
            )
        )
        block_count = len([block for block in ir.blocks if block.block_type != "Annotation"])
        inferred_count = len(
            [
                block
                for block in ir.blocks
                if block.block_type != "Annotation" and block.certainty == "inferred"
            ]
        )
        direct_count = block_count - inferred_count
        line_count = len(ir.connections)
        return [
            f"model = {model};",
            f"originalModelName = {original};",
            f"layoutStrategy = {layout_strategy};",
            f"layoutDescription = {layout_description};",
            f"expectedBlockCount = {block_count};",
            f"expectedLineCount = {line_count};",
            f"directMappedBlockCount = {direct_count};",
            f"inferredBlockCount = {inferred_count};",
            "fprintf('[parsing] Replaying reconstruction facts parsed from Simulink Coder output for %s.\\n', originalModelName);",
            "fprintf('[block creation] Creating %d blocks: %d directly mapped and %d inferred helper blocks.\\n', expectedBlockCount, directMappedBlockCount, inferredBlockCount);",
            "fprintf('[inferred-block creation] Inferred block names include the word inferred.\\n');",
            "fprintf('[layout] %s: %s\\n', layoutStrategy, layoutDescription);",
            "if bdIsLoaded(model)",
            "    close_system(model, 0);",
            "end",
            "if exist([model '.slx'], 'file')",
            "    delete([model '.slx']);",
            "end",
            "new_system(model);",
            "open_system(model);",
            "",
        ]

    def _render_block(self, block: BlockIR) -> list[str]:
        if block.block_type == "Annotation":
            return []
        library = self.LIBRARY_BLOCKS.get(block.block_type)
        if not library:
            library = "simulink/User-Defined Functions/MATLAB Function"
        block_path_expr = f"[model '/{self._escape_single(block.name)}']"
        lines = [
            f"% {block.block_type}: {block.name}",
        ]
        if block.source_ref:
            lines.append(f"% Source trace: {block.source_ref} ({block.certainty})")
        if block.expression:
            lines.append(f"% C expression: {block.expression}")
        lines.append(
            f"add_block({self._mstring(library)}, {block_path_expr}, "
            "'MakeNameUnique', 'off');"
        )
        if block.position:
            pos = " ".join(str(part) for part in block.position)
            lines.append(f"set_param({block_path_expr}, 'Position', [{pos}]);")
        for key, value in block.parameters.items():
            matlab_key = self.PARAM_MAP.get(key)
            if not matlab_key:
                continue
            lines.append(
                f"set_param({block_path_expr}, {self._mstring(matlab_key)}, "
                f"{self._mstring(self._matlab_param_value(value))});"
            )
        if block.unmapped_code:
            lines.append(
                f"% Unmapped source preserved: {block.unmapped_code}"
            )
        lines.append("")
        return lines

    def _render_validation(self) -> list[str]:
        return [
            "% Validate expected top-level block and signal-line counts.",
            "fprintf('[validation] Checking top-level block and signal-line counts.\\n');",
            "actualBlockCount = numel(find_system(model, 'SearchDepth', 1, 'Type', 'Block'));",
            "actualLineCount = numel(find_system(model, 'FindAll', 'on', 'SearchDepth', 1, 'Type', 'line'));",
            "if actualBlockCount ~= expectedBlockCount",
            "    warning('Expected %d blocks, but found %d.', expectedBlockCount, actualBlockCount);",
            "end",
            "if actualLineCount ~= expectedLineCount",
            "    warning('Expected %d signal lines, but found %d.', expectedLineCount, actualLineCount);",
            "end",
            "",
        ]

    def _render_annotations(self, ir: ModelIR) -> list[str]:
        lines = ["% Add reconstruction notes and unmapped-code annotations."]
        notes = [
            "Layout strategy: "
            + ir.metadata.get("layout_strategy", "Left-to-right signal flow")
            + ". "
            + ir.metadata.get(
                "layout_description",
                "Blocks are arranged by dependency depth from sources to outputs.",
            )
        ]
        notes.extend(ir.annotations)
        notes.extend(f"Warning: {warning}" for warning in ir.warnings)
        if not notes:
            notes.append("No reconstruction warnings were recorded.")
        for index, note in enumerate(notes, start=1):
            text = self._mstring(self._shorten(note, 800))
            y = 30 + index * 45
            lines.append("try")
            lines.append(f"    ann = Simulink.Annotation(model, {text});")
            lines.append(f"    ann.Position = [30 {y} 520 {y + 35}];")
            lines.append("catch ME")
            lines.append("    warning('Could not add annotation: %s', ME.message);")
            lines.append("end")
        lines.append("")
        return lines

    @staticmethod
    def _matlab_param_value(value: str) -> str:
        value = str(value)
        value = value.replace("process_PIConstrained_P.", "")
        return value

    @staticmethod
    def _mstring(value: str) -> str:
        return "'" + MatlabWriter._escape_single(value) + "'"

    @staticmethod
    def _escape_single(value: str) -> str:
        return str(value).replace("'", "''")

    @staticmethod
    def _shorten(value: str, limit: int) -> str:
        if len(value) <= limit:
            return value
        return value[: limit - 3] + "..."
