% Auto-generated by the Python Simulink C reconstruction tool.
% The result is an approximate visualization and starting point.
% Generated from Simulink Coder C, which is not a lossless model format.
% Original model inferred from C: process_PIConstrained
% Layout strategy: Complex subsystem preferred.
% Layout note: A compact top-level diagram uses finer-grained subsystems for controller, delay, process, condenser, separator, steamjacket, evaporator, and inferred parameter helpers.
% Inferred facts are represented as blocks, lines, and annotations.

model = 'reconstructed_model_layout7_complex_subsystems';
originalModelName = 'process_PIConstrained';
layoutStrategy = 'Complex subsystem preferred';
layoutDescription = 'A compact top-level diagram uses finer-grained subsystems for controller, delay, process, condenser, separator, steamjacket, evaporator, and inferred parameter helpers.';
expectedBlockCount = 140;
expectedLineCount = 142;
directMappedBlockCount = 55;
inferredBlockCount = 12;
originalRecoveredBlockCount = 67;
subsystemCount = 8;
fprintf('[parsing] Replaying reconstruction facts parsed from Simulink Coder output for %s.\n', originalModelName);
fprintf('[block creation] Creating %d generated blocks from %d recovered logic blocks.\n', expectedBlockCount, originalRecoveredBlockCount);
fprintf('[inferred-block creation] Inferred logic block names include the word inferred.\n');
fprintf('[layout] %s: %s\n', layoutStrategy, layoutDescription);
fprintf('[layout] Preferred subsystem count: %d.\n', subsystemCount);
if bdIsLoaded(model)
    close_system(model, 0);
end
if exist([model '.slx'], 'file')
    delete([model '.slx']);
end
new_system(model);
open_system(model);

% Add top-level interface blocks.
% Outport: L2
% C expression: process_PIConstrained_B.Saturation
add_block('simulink/Sinks/Out1', [model '/L2'], 'MakeNameUnique', 'off');
set_param([model '/L2'], 'Position', [840 110 910 142]);
set_param([model '/L2'], 'Port', '1');

% Add preferred subsystem shells.
% Subsystem: Root_Controller
add_block('simulink/Ports & Subsystems/Subsystem', [model '/Root_Controller'], 'MakeNameUnique', 'off');
set_param([model '/Root_Controller'], 'Position', [150 95 325 167]);
try, delete_block([model '/Root_Controller/In1']); catch, end
try, delete_block([model '/Root_Controller/Out1']); catch, end

% Subsystem: Delay
add_block('simulink/Ports & Subsystems/Subsystem', [model '/Delay'], 'MakeNameUnique', 'off');
set_param([model '/Delay'], 'Position', [390 95 565 167]);
try, delete_block([model '/Delay/In1']); catch, end
try, delete_block([model '/Delay/Out1']); catch, end

% Subsystem: Whole_Process
add_block('simulink/Ports & Subsystems/Subsystem', [model '/Whole_Process'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process'], 'Position', [630 95 805 167]);
try, delete_block([model '/Whole_Process/In1']); catch, end
try, delete_block([model '/Whole_Process/Out1']); catch, end

% Subsystem: Condenser
add_block('simulink/Ports & Subsystems/Subsystem', [model '/Condenser'], 'MakeNameUnique', 'off');
set_param([model '/Condenser'], 'Position', [150 230 325 302]);
try, delete_block([model '/Condenser/In1']); catch, end
try, delete_block([model '/Condenser/Out1']); catch, end

% Subsystem: Separator
add_block('simulink/Ports & Subsystems/Subsystem', [model '/Separator'], 'MakeNameUnique', 'off');
set_param([model '/Separator'], 'Position', [390 230 565 302]);
try, delete_block([model '/Separator/In1']); catch, end
try, delete_block([model '/Separator/Out1']); catch, end

% Subsystem: Steamjacket
add_block('simulink/Ports & Subsystems/Subsystem', [model '/Steamjacket'], 'MakeNameUnique', 'off');
set_param([model '/Steamjacket'], 'Position', [630 230 805 302]);
try, delete_block([model '/Steamjacket/In1']); catch, end
try, delete_block([model '/Steamjacket/Out1']); catch, end

% Subsystem: Evaporator
add_block('simulink/Ports & Subsystems/Subsystem', [model '/Evaporator'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator'], 'Position', [150 365 325 437]);
try, delete_block([model '/Evaporator/In1']); catch, end
try, delete_block([model '/Evaporator/Out1']); catch, end

% Subsystem: Inferred_Parameters
add_block('simulink/Ports & Subsystems/Subsystem', [model '/Inferred_Parameters'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters'], 'Position', [390 365 565 437]);
try, delete_block([model '/Inferred_Parameters/In1']); catch, end
try, delete_block([model '/Inferred_Parameters/Out1']); catch, end

% Populate subsystem contents.
% Subsystem Inport: Root_Controller/in_Saturation_1
add_block('simulink/Sources/In1', [model '/Root_Controller/in_Saturation_1'], 'MakeNameUnique', 'off');
set_param([model '/Root_Controller/in_Saturation_1'], 'Position', [30 60 60 78]);
set_param([model '/Root_Controller/in_Saturation_1'], 'Port', '1');

% Subsystem Inport: Root_Controller/in_F2_Value_2
add_block('simulink/Sources/In1', [model '/Root_Controller/in_F2_Value_2'], 'MakeNameUnique', 'off');
set_param([model '/Root_Controller/in_F2_Value_2'], 'Position', [30 102 60 120]);
set_param([model '/Root_Controller/in_F2_Value_2'], 'Port', '2');

% Subsystem Outport: Root_Controller/out_Sum1_g_1
add_block('simulink/Sinks/Out1', [model '/Root_Controller/out_Sum1_g_1'], 'MakeNameUnique', 'off');
set_param([model '/Root_Controller/out_Sum1_g_1'], 'Position', [1078 60 1113 78]);
set_param([model '/Root_Controller/out_Sum1_g_1'], 'Port', '1');

% Subsystem Outport: Root_Controller/out_F1_Step_2
add_block('simulink/Sinks/Out1', [model '/Root_Controller/out_F1_Step_2'], 'MakeNameUnique', 'off');
set_param([model '/Root_Controller/out_F1_Step_2'], 'Position', [1078 102 1113 120]);
set_param([model '/Root_Controller/out_F1_Step_2'], 'Port', '2');

% Subsystem Outport: Root_Controller/out_F1_Step_3
add_block('simulink/Sinks/Out1', [model '/Root_Controller/out_F1_Step_3'], 'MakeNameUnique', 'off');
set_param([model '/Root_Controller/out_F1_Step_3'], 'Position', [1078 144 1113 162]);
set_param([model '/Root_Controller/out_F1_Step_3'], 'Port', '3');

% Subsystem Outport: Root_Controller/out_F1_Step_4
add_block('simulink/Sinks/Out1', [model '/Root_Controller/out_F1_Step_4'], 'MakeNameUnique', 'off');
set_param([model '/Root_Controller/out_F1_Step_4'], 'Position', [1078 186 1113 204]);
set_param([model '/Root_Controller/out_F1_Step_4'], 'Port', '4');

% Subsystem Outport: Root_Controller/out_X1_Step_5
add_block('simulink/Sinks/Out1', [model '/Root_Controller/out_X1_Step_5'], 'MakeNameUnique', 'off');
set_param([model '/Root_Controller/out_X1_Step_5'], 'Position', [1078 228 1113 246]);
set_param([model '/Root_Controller/out_X1_Step_5'], 'Port', '5');

% Subsystem Outport: Root_Controller/out_F1_Step_6
add_block('simulink/Sinks/Out1', [model '/Root_Controller/out_F1_Step_6'], 'MakeNameUnique', 'off');
set_param([model '/Root_Controller/out_F1_Step_6'], 'Position', [1078 270 1113 288]);
set_param([model '/Root_Controller/out_F1_Step_6'], 'Port', '6');

% Step: Root_F1_Step
% Source trace: <Root>/F1_Step (certain)
% C expression: process_PIConstrained_P.F1_Step_Y0
add_block('simulink/Sources/Step', [model '/Root_Controller/Root_F1_Step'], 'MakeNameUnique', 'off');
set_param([model '/Root_Controller/Root_F1_Step'], 'Position', [160 70 250 110]);
set_param([model '/Root_Controller/Root_F1_Step'], 'Time', '200.0');
set_param([model '/Root_Controller/Root_F1_Step'], 'Before', '10.0');
set_param([model '/Root_Controller/Root_F1_Step'], 'After', '10.0');

% Integrator: Root_FeedbackInt
% Source trace: <Root>/FeedbackInt (certain)
% C expression: process_PIConstrained_B.Ti
add_block('simulink/Continuous/Integrator', [model '/Root_Controller/Root_FeedbackInt'], 'MakeNameUnique', 'off');
set_param([model '/Root_Controller/Root_FeedbackInt'], 'Position', [660 70 772 122]);
set_param([model '/Root_Controller/Root_FeedbackInt'], 'InitialCondition', '0.0');

% Step: Root_L2_Set_Point
% Source trace: <Root>/L2 Set Point (certain)
% C expression: process_PIConstrained_P.L2SetPoint_Y0
add_block('simulink/Sources/Step', [model '/Root_Controller/Root_L2_Set_Point'], 'MakeNameUnique', 'off');
set_param([model '/Root_Controller/Root_L2_Set_Point'], 'Position', [160 124 280 164]);
set_param([model '/Root_Controller/Root_L2_Set_Point'], 'Time', '200.0');
set_param([model '/Root_Controller/Root_L2_Set_Point'], 'Before', '1.0');
set_param([model '/Root_Controller/Root_L2_Set_Point'], 'After', '1.0');

% Sum: Root_Sum
% Source trace: <Root>/Sum (certain)
% C expression: process_PIConstrained_B.L2SetPoint - process_PIConstrained_B.Saturation
add_block('simulink/Math Operations/Sum', [model '/Root_Controller/Root_Sum'], 'MakeNameUnique', 'off');
set_param([model '/Root_Controller/Root_Sum'], 'Position', [285 70 343 112]);
set_param([model '/Root_Controller/Root_Sum'], 'Inputs', '+-');

% Gain: S1_Slider_Gain
% Source trace: <S1>/Slider Gain (certain)
% C expression: process_PIConstrained_P.L2ProportionalGain_gain * process_PIConstrained_B.Sum_k
add_block('simulink/Math Operations/Gain', [model '/Root_Controller/S1_Slider_Gain'], 'MakeNameUnique', 'off');
set_param([model '/Root_Controller/S1_Slider_Gain'], 'Position', [410 70 512 110]);
set_param([model '/Root_Controller/S1_Slider_Gain'], 'Gain', '-14.18');

% Sum: Root_Sum2
% Source trace: <Root>/Sum2 (certain)
% C expression: process_PIConstrained_B.SliderGain + process_PIConstrained_B.FeedbackInt
add_block('simulink/Math Operations/Sum', [model '/Root_Controller/Root_Sum2'], 'MakeNameUnique', 'off');
set_param([model '/Root_Controller/Root_Sum2'], 'Position', [785 70 843 112]);
set_param([model '/Root_Controller/Root_Sum2'], 'Inputs', '++');

% Sum: Root_Sum1
% Source trace: <Root>/Sum1 (certain)
% C expression: process_PIConstrained_P.F2_Value + process_PIConstrained_B.Sum2_oi
add_block('simulink/Math Operations/Sum', [model '/Root_Controller/Root_Sum1'], 'MakeNameUnique', 'off');
set_param([model '/Root_Controller/Root_Sum1'], 'Position', [910 70 968 112]);
set_param([model '/Root_Controller/Root_Sum1'], 'Inputs', '++');

% Gain: Root_Ti
% Source trace: <Root>/Ti (certain)
% C expression: process_PIConstrained_P.Ti_Gain * process_PIConstrained_B.SliderGain
add_block('simulink/Math Operations/Gain', [model '/Root_Controller/Root_Ti'], 'MakeNameUnique', 'off');
set_param([model '/Root_Controller/Root_Ti'], 'Position', [535 70 609 110]);
set_param([model '/Root_Controller/Root_Ti'], 'Gain', '0.052826201796090863');

% Step: Root_X1_Step
% Source trace: <Root>/X1_Step (certain)
% C expression: process_PIConstrained_P.X1_Step_Y0
add_block('simulink/Sources/Step', [model '/Root_Controller/Root_X1_Step'], 'MakeNameUnique', 'off');
set_param([model '/Root_Controller/Root_X1_Step'], 'Position', [160 178 250 218]);
set_param([model '/Root_Controller/Root_X1_Step'], 'Time', '200.0');
set_param([model '/Root_Controller/Root_X1_Step'], 'Before', '5.0');
set_param([model '/Root_Controller/Root_X1_Step'], 'After', '35.0');

% Subsystem Inport: Delay/in_Sum1_g_1
add_block('simulink/Sources/In1', [model '/Delay/in_Sum1_g_1'], 'MakeNameUnique', 'off');
set_param([model '/Delay/in_Sum1_g_1'], 'Position', [30 60 60 78]);
set_param([model '/Delay/in_Sum1_g_1'], 'Port', '1');

% Subsystem Outport: Delay/out_Integrator_1
add_block('simulink/Sinks/Out1', [model '/Delay/out_Integrator_1'], 'MakeNameUnique', 'off');
set_param([model '/Delay/out_Integrator_1'], 'Position', [882 60 917 78]);
set_param([model '/Delay/out_Integrator_1'], 'Port', '1');

% Integrator: S3_Integrator
% Source trace: <S3>/Integrator (certain)
% C expression: process_PIConstrained_B.Gain_b
add_block('simulink/Continuous/Integrator', [model '/Delay/S3_Integrator'], 'MakeNameUnique', 'off');
set_param([model '/Delay/S3_Integrator'], 'Position', [660 70 772 122]);
set_param([model '/Delay/S3_Integrator'], 'InitialCondition', '0.0');

% Sum: S3_Sum
% Source trace: <S3>/Sum (certain)
% C expression: process_PIConstrained_B.Sum1_g - process_PIConstrained_B.Integrator
add_block('simulink/Math Operations/Sum', [model '/Delay/S3_Sum'], 'MakeNameUnique', 'off');
set_param([model '/Delay/S3_Sum'], 'Position', [410 70 468 112]);
set_param([model '/Delay/S3_Sum'], 'Inputs', '+-');

% Gain: S3_Gain
% Source trace: <S3>/Gain (certain)
% C expression: process_PIConstrained_P.Gain_Gain_hu * process_PIConstrained_B.Sum_iw
add_block('simulink/Math Operations/Gain', [model '/Delay/S3_Gain'], 'MakeNameUnique', 'off');
set_param([model '/Delay/S3_Gain'], 'Position', [535 70 609 110]);
set_param([model '/Delay/S3_Gain'], 'Gain', '0.83333333333333337');

% Subsystem Inport: Whole_Process/in_L2Int_1
add_block('simulink/Sources/In1', [model '/Whole_Process/in_L2Int_1'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/in_L2Int_1'], 'Position', [30 60 60 78]);
set_param([model '/Whole_Process/in_L2Int_1'], 'Port', '1');

% Subsystem Inport: Whole_Process/in_P100_Value_2
add_block('simulink/Sources/In1', [model '/Whole_Process/in_P100_Value_2'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/in_P100_Value_2'], 'Position', [30 102 60 120]);
set_param([model '/Whole_Process/in_P100_Value_2'], 'Port', '2');

% Subsystem Inport: Whole_Process/in_Integrator_3
add_block('simulink/Sources/In1', [model '/Whole_Process/in_Integrator_3'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/in_Integrator_3'], 'Position', [30 144 60 162]);
set_param([model '/Whole_Process/in_Integrator_3'], 'Port', '3');

% Subsystem Inport: Whole_Process/in_Saturation_p_4
add_block('simulink/Sources/In1', [model '/Whole_Process/in_Saturation_p_4'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/in_Saturation_p_4'], 'Position', [30 186 60 204]);
set_param([model '/Whole_Process/in_Saturation_p_4'], 'Port', '4');

% Subsystem Inport: Whole_Process/in_Gain1_a_5
add_block('simulink/Sources/In1', [model '/Whole_Process/in_Gain1_a_5'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/in_Gain1_a_5'], 'Position', [30 228 60 246]);
set_param([model '/Whole_Process/in_Gain1_a_5'], 'Port', '5');

% Subsystem Inport: Whole_Process/in_F200_Value_6
add_block('simulink/Sources/In1', [model '/Whole_Process/in_F200_Value_6'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/in_F200_Value_6'], 'Position', [30 270 60 288]);
set_param([model '/Whole_Process/in_F200_Value_6'], 'Port', '6');

% Subsystem Outport: Whole_Process/out_Saturation_1
add_block('simulink/Sinks/Out1', [model '/Whole_Process/out_Saturation_1'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/out_Saturation_1'], 'Position', [366 60 401 78]);
set_param([model '/Whole_Process/out_Saturation_1'], 'Port', '1');

% Subsystem Outport: Whole_Process/out_Saturation_2
add_block('simulink/Sinks/Out1', [model '/Whole_Process/out_Saturation_2'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/out_Saturation_2'], 'Position', [366 102 401 120]);
set_param([model '/Whole_Process/out_Saturation_2'], 'Port', '2');

% Subsystem Outport: Whole_Process/out_Saturation6_3
add_block('simulink/Sinks/Out1', [model '/Whole_Process/out_Saturation6_3'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/out_Saturation6_3'], 'Position', [366 144 401 162]);
set_param([model '/Whole_Process/out_Saturation6_3'], 'Port', '3');

% Subsystem Outport: Whole_Process/out_Saturation3_4
add_block('simulink/Sinks/Out1', [model '/Whole_Process/out_Saturation3_4'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/out_Saturation3_4'], 'Position', [366 186 401 204]);
set_param([model '/Whole_Process/out_Saturation3_4'], 'Port', '4');

% Subsystem Outport: Whole_Process/out_Saturation4_5
add_block('simulink/Sinks/Out1', [model '/Whole_Process/out_Saturation4_5'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/out_Saturation4_5'], 'Position', [366 228 401 246]);
set_param([model '/Whole_Process/out_Saturation4_5'], 'Port', '5');

% Subsystem Outport: Whole_Process/out_Saturation2_6
add_block('simulink/Sinks/Out1', [model '/Whole_Process/out_Saturation2_6'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/out_Saturation2_6'], 'Position', [366 270 401 288]);
set_param([model '/Whole_Process/out_Saturation2_6'], 'Port', '6');

% Subsystem Outport: Whole_Process/out_Saturation3_7
add_block('simulink/Sinks/Out1', [model '/Whole_Process/out_Saturation3_7'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/out_Saturation3_7'], 'Position', [366 312 401 330]);
set_param([model '/Whole_Process/out_Saturation3_7'], 'Port', '7');

% Subsystem Outport: Whole_Process/out_Saturation5_8
add_block('simulink/Sinks/Out1', [model '/Whole_Process/out_Saturation5_8'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/out_Saturation5_8'], 'Position', [366 354 401 372]);
set_param([model '/Whole_Process/out_Saturation5_8'], 'Port', '8');

% Saturation: S2_Saturation
% Source trace: <S2>/Saturation (certain)
% C expression: (process_PIConstrained_P.Saturation_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/Whole_Process/S2_Saturation'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/S2_Saturation'], 'Position', [160 70 256 112]);
set_param([model '/Whole_Process/S2_Saturation'], 'LowerLimit', '0.0');
set_param([model '/Whole_Process/S2_Saturation'], 'UpperLimit', '2.0');

% Saturation: S2_Saturation2
% Source trace: <S2>/Saturation2 (certain)
% C expression: (process_PIConstrained_P.Saturation2_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/Whole_Process/S2_Saturation2'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/S2_Saturation2'], 'Position', [160 124 256 166]);
set_param([model '/Whole_Process/S2_Saturation2'], 'LowerLimit', '0.0');
set_param([model '/Whole_Process/S2_Saturation2'], 'UpperLimit', '400.0');

% Saturation: S2_Saturation4
% Source trace: <S2>/Saturation4 (certain)
% C expression: (process_PIConstrained_P.Saturation4_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/Whole_Process/S2_Saturation4'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/S2_Saturation4'], 'Position', [160 232 256 274]);
set_param([model '/Whole_Process/S2_Saturation4'], 'LowerLimit', '0.0');
set_param([model '/Whole_Process/S2_Saturation4'], 'UpperLimit', '16.0');

% Saturation: S2_Saturation6
% Source trace: <S2>/Saturation6 (certain)
% C expression: (process_PIConstrained_P.Saturation6_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/Whole_Process/S2_Saturation6'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/S2_Saturation6'], 'Position', [160 340 256 382]);
set_param([model '/Whole_Process/S2_Saturation6'], 'LowerLimit', '0.0');
set_param([model '/Whole_Process/S2_Saturation6'], 'UpperLimit', '416.0');

% Saturation: S2_Saturation3
% Source trace: <S2>/Saturation3 (certain)
% C expression: (process_PIConstrained_P.Saturation3_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/Whole_Process/S2_Saturation3'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/S2_Saturation3'], 'Position', [160 178 256 220]);
set_param([model '/Whole_Process/S2_Saturation3'], 'LowerLimit', '0.0');
set_param([model '/Whole_Process/S2_Saturation3'], 'UpperLimit', '4.0');

% Saturation: S2_Saturation5
% Source trace: <S2>/Saturation5 (certain)
% C expression: (process_PIConstrained_P.Saturation5_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/Whole_Process/S2_Saturation5'], 'MakeNameUnique', 'off');
set_param([model '/Whole_Process/S2_Saturation5'], 'Position', [160 286 256 328]);
set_param([model '/Whole_Process/S2_Saturation5'], 'LowerLimit', '0.0');
set_param([model '/Whole_Process/S2_Saturation5'], 'UpperLimit', '16.0');

% Subsystem Inport: Condenser/in_Constant_Value_c_1
add_block('simulink/Sources/In1', [model '/Condenser/in_Constant_Value_c_1'], 'MakeNameUnique', 'off');
set_param([model '/Condenser/in_Constant_Value_c_1'], 'Position', [30 60 60 78]);
set_param([model '/Condenser/in_Constant_Value_c_1'], 'Port', '1');

% Subsystem Inport: Condenser/in_Constant1_Value_h_2
add_block('simulink/Sources/In1', [model '/Condenser/in_Constant1_Value_h_2'], 'MakeNameUnique', 'off');
set_param([model '/Condenser/in_Constant1_Value_h_2'], 'Position', [30 102 60 120]);
set_param([model '/Condenser/in_Constant1_Value_h_2'], 'Port', '2');

% Subsystem Inport: Condenser/in_Saturation6_3
add_block('simulink/Sources/In1', [model '/Condenser/in_Saturation6_3'], 'MakeNameUnique', 'off');
set_param([model '/Condenser/in_Saturation6_3'], 'Position', [30 144 60 162]);
set_param([model '/Condenser/in_Saturation6_3'], 'Port', '3');

% Subsystem Inport: Condenser/in_Sum3_4
add_block('simulink/Sources/In1', [model '/Condenser/in_Sum3_4'], 'MakeNameUnique', 'off');
set_param([model '/Condenser/in_Sum3_4'], 'Position', [30 186 60 204]);
set_param([model '/Condenser/in_Sum3_4'], 'Port', '4');

% Subsystem Inport: Condenser/in_T200_Value_5
add_block('simulink/Sources/In1', [model '/Condenser/in_T200_Value_5'], 'MakeNameUnique', 'off');
set_param([model '/Condenser/in_T200_Value_5'], 'Position', [30 228 60 246]);
set_param([model '/Condenser/in_T200_Value_5'], 'Port', '5');

% Subsystem Inport: Condenser/in_Constant2_Value_6
add_block('simulink/Sources/In1', [model '/Condenser/in_Constant2_Value_6'], 'MakeNameUnique', 'off');
set_param([model '/Condenser/in_Constant2_Value_6'], 'Position', [30 270 60 288]);
set_param([model '/Condenser/in_Constant2_Value_6'], 'Port', '6');

% Subsystem Outport: Condenser/out_Gain1_a_1
add_block('simulink/Sinks/Out1', [model '/Condenser/out_Gain1_a_1'], 'MakeNameUnique', 'off');
set_param([model '/Condenser/out_Gain1_a_1'], 'Position', [719 60 754 78]);
set_param([model '/Condenser/out_Gain1_a_1'], 'Port', '1');

% Sum: S4_Sum
% Source trace: <S4>/Sum (certain)
% C expression: process_PIConstrained_B.Sum3 - process_PIConstrained_P.T200_Value
add_block('simulink/Math Operations/Sum', [model '/Condenser/S4_Sum'], 'MakeNameUnique', 'off');
set_param([model '/Condenser/S4_Sum'], 'Position', [160 124 218 166]);
set_param([model '/Condenser/S4_Sum'], 'Inputs', '+-');

% Gain: S4_Gain
% Source trace: <S4>/Gain (certain)
% C expression: process_PIConstrained_P.Gain_Gain_h * process_PIConstrained_B.Sum_d
add_block('simulink/Math Operations/Gain', [model '/Condenser/S4_Gain'], 'MakeNameUnique', 'off');
set_param([model '/Condenser/S4_Gain'], 'Position', [285 70 359 110]);
set_param([model '/Condenser/S4_Gain'], 'Gain', '6.84');

% Product: S4_Product
% Source trace: <S4>/Product (certain)
% C expression: process_PIConstrained_P.Constant_Value_c / process_PIConstrained_P.Constant1_Value_h / process_PIConstrained_B.Saturation6
add_block('simulink/Math Operations/Product', [model '/Condenser/S4_Product'], 'MakeNameUnique', 'off');
set_param([model '/Condenser/S4_Product'], 'Position', [160 70 218 112]);
set_param([model '/Condenser/S4_Product'], 'Inputs', '*//');

% Sum: S4_Sum1
% Source trace: <S4>/Sum1 (certain)
% C expression: process_PIConstrained_P.Constant2_Value + process_PIConstrained_B.Product_k
add_block('simulink/Math Operations/Sum', [model '/Condenser/S4_Sum1'], 'MakeNameUnique', 'off');
set_param([model '/Condenser/S4_Sum1'], 'Position', [285 124 343 166]);
set_param([model '/Condenser/S4_Sum1'], 'Inputs', '++');

% Product: S4_Product1
% Source trace: <S4>/Product1 (certain)
% C expression: process_PIConstrained_B.Gain_c / process_PIConstrained_B.Sum1_h
add_block('simulink/Math Operations/Product', [model '/Condenser/S4_Product1'], 'MakeNameUnique', 'off');
set_param([model '/Condenser/S4_Product1'], 'Position', [410 70 468 112]);
set_param([model '/Condenser/S4_Product1'], 'Inputs', '*/');

% Gain: S4_Gain1
% Source trace: <S4>/Gain1 (certain)
% C expression: process_PIConstrained_P.Gain1_Gain_l * process_PIConstrained_B.Q200
add_block('simulink/Math Operations/Gain', [model '/Condenser/S4_Gain1'], 'MakeNameUnique', 'off');
set_param([model '/Condenser/S4_Gain1'], 'Position', [535 70 609 110]);
set_param([model '/Condenser/S4_Gain1'], 'Gain', '0.025974025974025976');

% Subsystem Inport: Separator/in_F1_Step_1
add_block('simulink/Sources/In1', [model '/Separator/in_F1_Step_1'], 'MakeNameUnique', 'off');
set_param([model '/Separator/in_F1_Step_1'], 'Position', [30 60 60 78]);
set_param([model '/Separator/in_F1_Step_1'], 'Port', '1');

% Subsystem Inport: Separator/in_Saturation3_2
add_block('simulink/Sources/In1', [model '/Separator/in_Saturation3_2'], 'MakeNameUnique', 'off');
set_param([model '/Separator/in_Saturation3_2'], 'Position', [30 102 60 120]);
set_param([model '/Separator/in_Saturation3_2'], 'Port', '2');

% Subsystem Inport: Separator/in_Saturation4_3
add_block('simulink/Sources/In1', [model '/Separator/in_Saturation4_3'], 'MakeNameUnique', 'off');
set_param([model '/Separator/in_Saturation4_3'], 'Position', [30 144 60 162]);
set_param([model '/Separator/in_Saturation4_3'], 'Port', '3');

% Subsystem Outport: Separator/out_L2Int_1
add_block('simulink/Sinks/Out1', [model '/Separator/out_L2Int_1'], 'MakeNameUnique', 'off');
set_param([model '/Separator/out_L2Int_1'], 'Position', [632 60 667 78]);
set_param([model '/Separator/out_L2Int_1'], 'Port', '1');

% Integrator: S5_L2Int
% Source trace: <S5>/L2Int (certain)
% C expression: process_PIConstrained_B.Gain_g
add_block('simulink/Continuous/Integrator', [model '/Separator/S5_L2Int'], 'MakeNameUnique', 'off');
set_param([model '/Separator/S5_L2Int'], 'Position', [410 70 522 122]);
set_param([model '/Separator/S5_L2Int'], 'InitialCondition', '1.0');

% Sum: S5_Sum
% Source trace: <S5>/Sum (certain)
% C expression: (process_PIConstrained_B.F1_Step - process_PIConstrained_B.Saturation3) - process_PIConstrained_B.Saturation4
add_block('simulink/Math Operations/Sum', [model '/Separator/S5_Sum'], 'MakeNameUnique', 'off');
set_param([model '/Separator/S5_Sum'], 'Position', [160 70 218 112]);
set_param([model '/Separator/S5_Sum'], 'Inputs', '+--');

% Gain: S5_Gain
% Source trace: <S5>/Gain (certain)
% C expression: process_PIConstrained_P.Gain_Gain_k * process_PIConstrained_B.Sum_m
add_block('simulink/Math Operations/Gain', [model '/Separator/S5_Gain'], 'MakeNameUnique', 'off');
set_param([model '/Separator/S5_Gain'], 'Position', [285 70 359 110]);
set_param([model '/Separator/S5_Gain'], 'Gain', '0.05');

% Subsystem Inport: Steamjacket/in_Saturation2_1
add_block('simulink/Sources/In1', [model '/Steamjacket/in_Saturation2_1'], 'MakeNameUnique', 'off');
set_param([model '/Steamjacket/in_Saturation2_1'], 'Position', [30 60 60 78]);
set_param([model '/Steamjacket/in_Saturation2_1'], 'Port', '1');

% Subsystem Inport: Steamjacket/in_Constant1_Value_2
add_block('simulink/Sources/In1', [model '/Steamjacket/in_Constant1_Value_2'], 'MakeNameUnique', 'off');
set_param([model '/Steamjacket/in_Constant1_Value_2'], 'Position', [30 102 60 120]);
set_param([model '/Steamjacket/in_Constant1_Value_2'], 'Port', '2');

% Subsystem Inport: Steamjacket/in_F1_Step_3
add_block('simulink/Sources/In1', [model '/Steamjacket/in_F1_Step_3'], 'MakeNameUnique', 'off');
set_param([model '/Steamjacket/in_F1_Step_3'], 'Position', [30 144 60 162]);
set_param([model '/Steamjacket/in_F1_Step_3'], 'Port', '3');

% Subsystem Inport: Steamjacket/in_F3_Value_4
add_block('simulink/Sources/In1', [model '/Steamjacket/in_F3_Value_4'], 'MakeNameUnique', 'off');
set_param([model '/Steamjacket/in_F3_Value_4'], 'Position', [30 186 60 204]);
set_param([model '/Steamjacket/in_F3_Value_4'], 'Port', '4');

% Subsystem Inport: Steamjacket/in_Sum2_5
add_block('simulink/Sources/In1', [model '/Steamjacket/in_Sum2_5'], 'MakeNameUnique', 'off');
set_param([model '/Steamjacket/in_Sum2_5'], 'Position', [30 228 60 246]);
set_param([model '/Steamjacket/in_Sum2_5'], 'Port', '5');

% Subsystem Outport: Steamjacket/out_Product_1
add_block('simulink/Sinks/Out1', [model '/Steamjacket/out_Product_1'], 'MakeNameUnique', 'off');
set_param([model '/Steamjacket/out_Product_1'], 'Position', [703 60 738 78]);
set_param([model '/Steamjacket/out_Product_1'], 'Port', '1');

% Sum: S6_Sum1
% Source trace: <S6>/Sum1 (certain)
% C expression: process_PIConstrained_B.F1_Step + process_PIConstrained_P.F3_Value
add_block('simulink/Math Operations/Sum', [model '/Steamjacket/S6_Sum1'], 'MakeNameUnique', 'off');
set_param([model '/Steamjacket/S6_Sum1'], 'Position', [160 124 218 166]);
set_param([model '/Steamjacket/S6_Sum1'], 'Inputs', '++');

% Gain: S6_Gain1
% Source trace: <S6>/Gain1 (certain)
% C expression: process_PIConstrained_P.Gain1_Gain * process_PIConstrained_B.Sum1
add_block('simulink/Math Operations/Gain', [model '/Steamjacket/S6_Gain1'], 'MakeNameUnique', 'off');
set_param([model '/Steamjacket/S6_Gain1'], 'Position', [285 70 359 110]);
set_param([model '/Steamjacket/S6_Gain1'], 'Gain', '0.16');

% Gain: S6_Gain
% Source trace: <S6>/Gain (certain)
% C expression: process_PIConstrained_P.Gain_Gain * process_PIConstrained_B.Saturation2
add_block('simulink/Math Operations/Gain', [model '/Steamjacket/S6_Gain'], 'MakeNameUnique', 'off');
set_param([model '/Steamjacket/S6_Gain'], 'Position', [160 70 234 110]);
set_param([model '/Steamjacket/S6_Gain'], 'Gain', '0.1538');

% Sum: S6_Sum
% Source trace: <S6>/Sum (certain)
% C expression: process_PIConstrained_P.Constant1_Value + process_PIConstrained_B.Gain
add_block('simulink/Math Operations/Sum', [model '/Steamjacket/S6_Sum'], 'MakeNameUnique', 'off');
set_param([model '/Steamjacket/S6_Sum'], 'Position', [285 124 343 166]);
set_param([model '/Steamjacket/S6_Sum'], 'Inputs', '++');

% Sum: S6_Sum2
% Source trace: <S6>/Sum2 (certain)
% C expression: process_PIConstrained_B.Sum - process_PIConstrained_B.Sum2
add_block('simulink/Math Operations/Sum', [model '/Steamjacket/S6_Sum2'], 'MakeNameUnique', 'off');
set_param([model '/Steamjacket/S6_Sum2'], 'Position', [410 70 468 112]);
set_param([model '/Steamjacket/S6_Sum2'], 'Inputs', '+-');

% Product: S6_Product
% Source trace: <S6>/Product (certain)
% C expression: process_PIConstrained_B.Gain1 * process_PIConstrained_B.Sum2_o
add_block('simulink/Math Operations/Product', [model '/Steamjacket/S6_Product'], 'MakeNameUnique', 'off');
set_param([model '/Steamjacket/S6_Product'], 'Position', [535 70 593 112]);
set_param([model '/Steamjacket/S6_Product'], 'Inputs', '**');

% Subsystem Inport: Evaporator/in_F1_Step_1
add_block('simulink/Sources/In1', [model '/Evaporator/in_F1_Step_1'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/in_F1_Step_1'], 'Position', [30 60 60 78]);
set_param([model '/Evaporator/in_F1_Step_1'], 'Port', '1');

% Subsystem Inport: Evaporator/in_X1_Step_2
add_block('simulink/Sources/In1', [model '/Evaporator/in_X1_Step_2'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/in_X1_Step_2'], 'Position', [30 102 60 120]);
set_param([model '/Evaporator/in_X1_Step_2'], 'Port', '2');

% Subsystem Inport: Evaporator/in_Saturation3_3
add_block('simulink/Sources/In1', [model '/Evaporator/in_Saturation3_3'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/in_Saturation3_3'], 'Position', [30 144 60 162]);
set_param([model '/Evaporator/in_Saturation3_3'], 'Port', '3');

% Subsystem Inport: Evaporator/in_F1_Step_4
add_block('simulink/Sources/In1', [model '/Evaporator/in_F1_Step_4'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/in_F1_Step_4'], 'Position', [30 186 60 204]);
set_param([model '/Evaporator/in_F1_Step_4'], 'Port', '4');

% Subsystem Inport: Evaporator/in_Saturation5_5
add_block('simulink/Sources/In1', [model '/Evaporator/in_Saturation5_5'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/in_Saturation5_5'], 'Position', [30 228 60 246]);
set_param([model '/Evaporator/in_Saturation5_5'], 'Port', '5');

% Subsystem Inport: Evaporator/in_Constant_Value_6
add_block('simulink/Sources/In1', [model '/Evaporator/in_Constant_Value_6'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/in_Constant_Value_6'], 'Position', [30 270 60 288]);
set_param([model '/Evaporator/in_Constant_Value_6'], 'Port', '6');

% Subsystem Inport: Evaporator/in_Constant1_Value_i_7
add_block('simulink/Sources/In1', [model '/Evaporator/in_Constant1_Value_i_7'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/in_Constant1_Value_i_7'], 'Position', [30 312 60 330]);
set_param([model '/Evaporator/in_Constant1_Value_i_7'], 'Port', '7');

% Subsystem Inport: Evaporator/in_Product_8
add_block('simulink/Sources/In1', [model '/Evaporator/in_Product_8'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/in_Product_8'], 'Position', [30 354 60 372]);
set_param([model '/Evaporator/in_Product_8'], 'Port', '8');

% Subsystem Inport: Evaporator/in_T1_Value_9
add_block('simulink/Sources/In1', [model '/Evaporator/in_T1_Value_9'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/in_T1_Value_9'], 'Position', [30 396 60 414]);
set_param([model '/Evaporator/in_T1_Value_9'], 'Port', '9');

% Subsystem Outport: Evaporator/out_Saturation_p_1
add_block('simulink/Sinks/Out1', [model '/Evaporator/out_Saturation_p_1'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/out_Saturation_p_1'], 'Position', [1453 60 1488 78]);
set_param([model '/Evaporator/out_Saturation_p_1'], 'Port', '1');

% Subsystem Outport: Evaporator/out_Sum3_2
add_block('simulink/Sinks/Out1', [model '/Evaporator/out_Sum3_2'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/out_Sum3_2'], 'Position', [1453 102 1488 120]);
set_param([model '/Evaporator/out_Sum3_2'], 'Port', '2');

% Subsystem Outport: Evaporator/out_Sum2_3
add_block('simulink/Sinks/Out1', [model '/Evaporator/out_Sum2_3'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/out_Sum2_3'], 'Position', [1453 144 1488 162]);
set_param([model '/Evaporator/out_Sum2_3'], 'Port', '3');

% Integrator: S7_X2Int
% Source trace: <S7>/X2Int (certain)
% C expression: process_PIConstrained_B.Gain_a
add_block('simulink/Continuous/Integrator', [model '/Evaporator/S7_X2Int'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_X2Int'], 'Position', [785 70 897 122]);
set_param([model '/Evaporator/S7_X2Int'], 'InitialCondition', '25.0');

% Gain: S7_Gain3
% Source trace: <S7>/Gain3 (certain)
% C expression: process_PIConstrained_P.Gain3_Gain * process_PIConstrained_B.X2Int
add_block('simulink/Math Operations/Gain', [model '/Evaporator/S7_Gain3'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Gain3'], 'Position', [910 70 984 110]);
set_param([model '/Evaporator/S7_Gain3'], 'Gain', '0.3126');

% Integrator: S7_P2Int
% Source trace: <S7>/P2Int (certain)
% C expression: process_PIConstrained_B.Gain1_f
add_block('simulink/Continuous/Integrator', [model '/Evaporator/S7_P2Int'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_P2Int'], 'Position', [1035 286 1147 338]);
set_param([model '/Evaporator/S7_P2Int'], 'InitialCondition', '50.5');

% Saturation: S7_Saturation1
% Source trace: <S7>/Saturation1 (certain)
% C expression: (process_PIConstrained_P.Saturation1_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/Evaporator/S7_Saturation1'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Saturation1'], 'Position', [410 124 506 166]);
set_param([model '/Evaporator/S7_Saturation1'], 'LowerLimit', '0.0');
set_param([model '/Evaporator/S7_Saturation1'], 'UpperLimit', '100.0');

% Gain: S7_Gain2
% Source trace: <S7>/Gain2 (certain)
% C expression: process_PIConstrained_P.Gain2_Gain * process_PIConstrained_B.Saturation1
add_block('simulink/Math Operations/Gain', [model '/Evaporator/S7_Gain2'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Gain2'], 'Position', [535 70 609 110]);
set_param([model '/Evaporator/S7_Gain2'], 'Gain', '0.5616');

% Sum: S7_Sum2
% Source trace: <S7>/Sum2 (certain)
% C expression: (process_PIConstrained_B.Gain3 + process_PIConstrained_P.Constant_Value) + process_PIConstrained_B.Gain2
add_block('simulink/Math Operations/Sum', [model '/Evaporator/S7_Sum2'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Sum2'], 'Position', [1035 70 1093 112]);
set_param([model '/Evaporator/S7_Sum2'], 'Inputs', '+++');

% Sum: S7_Sum5
% Source trace: <S7>/Sum5 (certain)
% C expression: process_PIConstrained_B.Sum2 - process_PIConstrained_P.T1_Value
add_block('simulink/Math Operations/Sum', [model '/Evaporator/S7_Sum5'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Sum5'], 'Position', [1160 70 1218 112]);
set_param([model '/Evaporator/S7_Sum5'], 'Inputs', '+-');

% Product: S7_Product2
% Source trace: <S7>/Product2 (certain)
% C expression: process_PIConstrained_B.Sum5 * process_PIConstrained_B.F1_Step
add_block('simulink/Math Operations/Product', [model '/Evaporator/S7_Product2'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Product2'], 'Position', [1285 70 1343 112]);
set_param([model '/Evaporator/S7_Product2'], 'Inputs', '**');

% Gain: S7_Gain5
% Source trace: <S7>/Gain5 (certain)
% C expression: process_PIConstrained_P.Gain5_Gain * process_PIConstrained_B.Product2
add_block('simulink/Math Operations/Gain', [model '/Evaporator/S7_Gain5'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Gain5'], 'Position', [160 286 234 326]);
set_param([model '/Evaporator/S7_Gain5'], 'Gain', '0.07');

% Sum: S7_Sum4
% Source trace: <S7>/Sum4 (certain)
% C expression: process_PIConstrained_B.Product - process_PIConstrained_B.Gain5
add_block('simulink/Math Operations/Sum', [model '/Evaporator/S7_Sum4'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Sum4'], 'Position', [285 286 343 328]);
set_param([model '/Evaporator/S7_Sum4'], 'Inputs', '+-');

% Gain: S7_Gain6
% Source trace: <S7>/Gain6 (certain)
% C expression: process_PIConstrained_P.Gain6_Gain * process_PIConstrained_B.Sum4
add_block('simulink/Math Operations/Gain', [model '/Evaporator/S7_Gain6'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Gain6'], 'Position', [410 286 484 326]);
set_param([model '/Evaporator/S7_Gain6'], 'Gain', '0.025974025974025976');

% Saturation: S7_Saturation
% Source trace: <S7>/Saturation (certain)
% C expression: (process_PIConstrained_P.Saturation_UpperSat_p)
add_block('simulink/Discontinuities/Saturation', [model '/Evaporator/S7_Saturation'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Saturation'], 'Position', [535 286 631 328]);
set_param([model '/Evaporator/S7_Saturation'], 'LowerLimit', '0.0');
set_param([model '/Evaporator/S7_Saturation'], 'UpperLimit', '16.0');

% Gain: S7_Gain4
% Source trace: <S7>/Gain4 (certain)
% C expression: process_PIConstrained_P.Gain4_Gain * process_PIConstrained_B.Saturation1
add_block('simulink/Math Operations/Gain', [model '/Evaporator/S7_Gain4'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Gain4'], 'Position', [535 124 609 164]);
set_param([model '/Evaporator/S7_Gain4'], 'Gain', '0.507');

% Sum: S7_Sum3
% Source trace: <S7>/Sum3 (certain)
% C expression: process_PIConstrained_B.Gain4 + process_PIConstrained_P.Constant1_Value_i
add_block('simulink/Math Operations/Sum', [model '/Evaporator/S7_Sum3'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Sum3'], 'Position', [660 124 718 166]);
set_param([model '/Evaporator/S7_Sum3'], 'Inputs', '++');

% Product: S7_Product
% Source trace: <S7>/Product (certain)
% C expression: process_PIConstrained_B.F1_Step * process_PIConstrained_B.X1_Step
add_block('simulink/Math Operations/Product', [model '/Evaporator/S7_Product'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Product'], 'Position', [160 70 218 112]);
set_param([model '/Evaporator/S7_Product'], 'Inputs', '**');

% Product: S7_Product1
% Source trace: <S7>/Product1 (certain)
% C expression: process_PIConstrained_B.Saturation3 * process_PIConstrained_B.X2Int
add_block('simulink/Math Operations/Product', [model '/Evaporator/S7_Product1'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Product1'], 'Position', [410 70 468 112]);
set_param([model '/Evaporator/S7_Product1'], 'Inputs', '**');

% Sum: S7_Sum
% Source trace: <S7>/Sum (certain)
% C expression: process_PIConstrained_B.Product_c - process_PIConstrained_B.Product1
add_block('simulink/Math Operations/Sum', [model '/Evaporator/S7_Sum'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Sum'], 'Position', [535 178 593 220]);
set_param([model '/Evaporator/S7_Sum'], 'Inputs', '+-');

% Gain: S7_Gain
% Source trace: <S7>/Gain (certain)
% C expression: process_PIConstrained_P.Gain_Gain_n * process_PIConstrained_B.Sum_i
add_block('simulink/Math Operations/Gain', [model '/Evaporator/S7_Gain'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Gain'], 'Position', [660 70 734 110]);
set_param([model '/Evaporator/S7_Gain'], 'Gain', '0.05');

% Saturation: S7_Saturation2
% Source trace: <S7>/Saturation2 (certain)
% C expression: (process_PIConstrained_P.Saturation2_UpperSat_l)
add_block('simulink/Discontinuities/Saturation', [model '/Evaporator/S7_Saturation2'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Saturation2'], 'Position', [660 286 756 328]);
set_param([model '/Evaporator/S7_Saturation2'], 'LowerLimit', '0.0');
set_param([model '/Evaporator/S7_Saturation2'], 'UpperLimit', '16.0');

% Sum: S7_Sum1
% Source trace: <S7>/Sum1 (certain)
% C expression: process_PIConstrained_B.Saturation2_e - process_PIConstrained_B.Saturation5
add_block('simulink/Math Operations/Sum', [model '/Evaporator/S7_Sum1'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Sum1'], 'Position', [785 286 843 328]);
set_param([model '/Evaporator/S7_Sum1'], 'Inputs', '+-');

% Gain: S7_Gain1
% Source trace: <S7>/Gain1 (certain)
% C expression: process_PIConstrained_P.Gain1_Gain_m * process_PIConstrained_B.Sum1_e
add_block('simulink/Math Operations/Gain', [model '/Evaporator/S7_Gain1'], 'MakeNameUnique', 'off');
set_param([model '/Evaporator/S7_Gain1'], 'Position', [910 286 984 326]);
set_param([model '/Evaporator/S7_Gain1'], 'Gain', '0.25');

% Subsystem Outport: Inferred_Parameters/out_F2_Value_1
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_F2_Value_1'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_F2_Value_1'], 'Position', [402 60 437 78]);
set_param([model '/Inferred_Parameters/out_F2_Value_1'], 'Port', '1');

% Subsystem Outport: Inferred_Parameters/out_P100_Value_2
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_P100_Value_2'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_P100_Value_2'], 'Position', [402 102 437 120]);
set_param([model '/Inferred_Parameters/out_P100_Value_2'], 'Port', '2');

% Subsystem Outport: Inferred_Parameters/out_F200_Value_3
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_F200_Value_3'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_F200_Value_3'], 'Position', [402 144 437 162]);
set_param([model '/Inferred_Parameters/out_F200_Value_3'], 'Port', '3');

% Subsystem Outport: Inferred_Parameters/out_Constant_Value_c_4
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_Constant_Value_c_4'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_Constant_Value_c_4'], 'Position', [402 186 437 204]);
set_param([model '/Inferred_Parameters/out_Constant_Value_c_4'], 'Port', '4');

% Subsystem Outport: Inferred_Parameters/out_Constant1_Value_h_5
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_Constant1_Value_h_5'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_Constant1_Value_h_5'], 'Position', [402 228 437 246]);
set_param([model '/Inferred_Parameters/out_Constant1_Value_h_5'], 'Port', '5');

% Subsystem Outport: Inferred_Parameters/out_T200_Value_6
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_T200_Value_6'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_T200_Value_6'], 'Position', [402 270 437 288]);
set_param([model '/Inferred_Parameters/out_T200_Value_6'], 'Port', '6');

% Subsystem Outport: Inferred_Parameters/out_Constant2_Value_7
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_Constant2_Value_7'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_Constant2_Value_7'], 'Position', [402 312 437 330]);
set_param([model '/Inferred_Parameters/out_Constant2_Value_7'], 'Port', '7');

% Subsystem Outport: Inferred_Parameters/out_Constant1_Value_8
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_Constant1_Value_8'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_Constant1_Value_8'], 'Position', [402 354 437 372]);
set_param([model '/Inferred_Parameters/out_Constant1_Value_8'], 'Port', '8');

% Subsystem Outport: Inferred_Parameters/out_F3_Value_9
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_F3_Value_9'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_F3_Value_9'], 'Position', [402 396 437 414]);
set_param([model '/Inferred_Parameters/out_F3_Value_9'], 'Port', '9');

% Subsystem Outport: Inferred_Parameters/out_Constant_Value_10
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_Constant_Value_10'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_Constant_Value_10'], 'Position', [402 438 437 456]);
set_param([model '/Inferred_Parameters/out_Constant_Value_10'], 'Port', '10');

% Subsystem Outport: Inferred_Parameters/out_Constant1_Value_i_11
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_Constant1_Value_i_11'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_Constant1_Value_i_11'], 'Position', [402 480 437 498]);
set_param([model '/Inferred_Parameters/out_Constant1_Value_i_11'], 'Port', '11');

% Subsystem Outport: Inferred_Parameters/out_T1_Value_12
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_T1_Value_12'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_T1_Value_12'], 'Position', [402 522 437 540]);
set_param([model '/Inferred_Parameters/out_T1_Value_12'], 'Port', '12');

% Constant: inferred_Const_F3_Value
% Source trace: <Root>/F3 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_F3_Value'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_F3_Value'], 'Position', [160 502 292 542]);
set_param([model '/Inferred_Parameters/inferred_Const_F3_Value'], 'Value', '50.0');

% Constant: inferred_Const_P100_Value
% Source trace: <Root>/P100 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_P100_Value'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_P100_Value'], 'Position', [160 556 292 596]);
set_param([model '/Inferred_Parameters/inferred_Const_P100_Value'], 'Value', '194.7');

% Constant: inferred_Const_Constant1_Value
% Source trace: <S6>/Constant1 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_Constant1_Value'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_Constant1_Value'], 'Position', [160 70 292 110]);
set_param([model '/Inferred_Parameters/inferred_Const_Constant1_Value'], 'Value', '90.0');

% Constant: inferred_Const_Constant_Value
% Source trace: <S7>/Constant (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_Constant_Value'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_Constant_Value'], 'Position', [160 286 292 326]);
set_param([model '/Inferred_Parameters/inferred_Const_Constant_Value'], 'Value', '48.43');

% Constant: inferred_Const_T1_Value
% Source trace: <Root>/T1 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_T1_Value'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_T1_Value'], 'Position', [160 610 292 650]);
set_param([model '/Inferred_Parameters/inferred_Const_T1_Value'], 'Value', '40.0');

% Constant: inferred_Const_F2_Value
% Source trace: <Root>/F2 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_F2_Value'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_F2_Value'], 'Position', [160 448 292 488]);
set_param([model '/Inferred_Parameters/inferred_Const_F2_Value'], 'Value', '2.0');

% Constant: inferred_Const_Constant1_Value_i
% Source trace: <S7>/Constant1 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_Constant1_Value_i'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_Constant1_Value_i'], 'Position', [160 178 292 218]);
set_param([model '/Inferred_Parameters/inferred_Const_Constant1_Value_i'], 'Value', '55.0');

% Constant: inferred_Const_T200_Value
% Source trace: <Root>/T200 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_T200_Value'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_T200_Value'], 'Position', [160 664 292 704]);
set_param([model '/Inferred_Parameters/inferred_Const_T200_Value'], 'Value', '25.0');

% Constant: inferred_Const_F200_Value
% Source trace: <Root>/F200 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_F200_Value'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_F200_Value'], 'Position', [160 394 292 434]);
set_param([model '/Inferred_Parameters/inferred_Const_F200_Value'], 'Value', '208.0');

% Constant: inferred_Const_Constant_Value_c
% Source trace: <S4>/Constant (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_Constant_Value_c'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_Constant_Value_c'], 'Position', [160 340 292 380]);
set_param([model '/Inferred_Parameters/inferred_Const_Constant_Value_c'], 'Value', '6.84');

% Constant: inferred_Const_Constant1_Value_h
% Source trace: <S4>/Constant1 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_Constant1_Value_h'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_Constant1_Value_h'], 'Position', [160 124 292 164]);
set_param([model '/Inferred_Parameters/inferred_Const_Constant1_Value_h'], 'Value', '0.14');

% Constant: inferred_Const_Constant2_Value
% Source trace: <S4>/Constant2 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_Constant2_Value'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_Constant2_Value'], 'Position', [160 232 292 272]);
set_param([model '/Inferred_Parameters/inferred_Const_Constant2_Value'], 'Value', '1.0');

% Connect internal subsystem signal dependencies.
fprintf('[connection] Creating %d generated signal lines, including subsystem bridge lines.\n', expectedLineCount);
try
    add_line([model '/Root_Controller'], 'Root_Ti/1', 'Root_FeedbackInt/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_Ti', 'Root_FeedbackInt', ME.message);
end
try
    add_line([model '/Root_Controller'], 'Root_L2_Set_Point/1', 'Root_Sum/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_L2_Set_Point', 'Root_Sum', ME.message);
end
try
    add_line([model '/Root_Controller'], 'in_Saturation_1/1', 'Root_Sum/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Saturation_1', 'Root_Sum', ME.message);
end
try
    add_line([model '/Root_Controller'], 'in_F2_Value_2/1', 'Root_Sum1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_F2_Value_2', 'Root_Sum1', ME.message);
end
try
    add_line([model '/Root_Controller'], 'Root_Sum2/1', 'Root_Sum1/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_Sum2', 'Root_Sum1', ME.message);
end
try
    add_line([model '/Root_Controller'], 'S1_Slider_Gain/1', 'Root_Sum2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S1_Slider_Gain', 'Root_Sum2', ME.message);
end
try
    add_line([model '/Root_Controller'], 'Root_FeedbackInt/1', 'Root_Sum2/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_FeedbackInt', 'Root_Sum2', ME.message);
end
try
    add_line([model '/Root_Controller'], 'S1_Slider_Gain/1', 'Root_Ti/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S1_Slider_Gain', 'Root_Ti', ME.message);
end
try
    add_line([model '/Root_Controller'], 'Root_Sum/1', 'S1_Slider_Gain/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_Sum', 'S1_Slider_Gain', ME.message);
end
try
    add_line([model '/Root_Controller'], 'Root_Sum1/1', 'out_Sum1_g_1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_Sum1', 'out_Sum1_g_1', ME.message);
end
try
    add_line([model '/Root_Controller'], 'Root_F1_Step/1', 'out_F1_Step_2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_F1_Step', 'out_F1_Step_2', ME.message);
end
try
    add_line([model '/Root_Controller'], 'Root_F1_Step/1', 'out_F1_Step_3/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_F1_Step', 'out_F1_Step_3', ME.message);
end
try
    add_line([model '/Root_Controller'], 'Root_F1_Step/1', 'out_F1_Step_4/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_F1_Step', 'out_F1_Step_4', ME.message);
end
try
    add_line([model '/Root_Controller'], 'Root_X1_Step/1', 'out_X1_Step_5/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_X1_Step', 'out_X1_Step_5', ME.message);
end
try
    add_line([model '/Root_Controller'], 'Root_F1_Step/1', 'out_F1_Step_6/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_F1_Step', 'out_F1_Step_6', ME.message);
end
try
    add_line([model '/Delay'], 'S3_Integrator/1', 'out_Integrator_1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S3_Integrator', 'out_Integrator_1', ME.message);
end
try
    add_line([model '/Delay'], 'S3_Sum/1', 'S3_Gain/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S3_Sum', 'S3_Gain', ME.message);
end
try
    add_line([model '/Delay'], 'S3_Gain/1', 'S3_Integrator/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S3_Gain', 'S3_Integrator', ME.message);
end
try
    add_line([model '/Delay'], 'in_Sum1_g_1/1', 'S3_Sum/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Sum1_g_1', 'S3_Sum', ME.message);
end
try
    add_line([model '/Delay'], 'S3_Integrator/1', 'S3_Sum/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S3_Integrator', 'S3_Sum', ME.message);
end
try
    add_line([model '/Whole_Process'], 'S2_Saturation/1', 'out_Saturation_1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation', 'out_Saturation_1', ME.message);
end
try
    add_line([model '/Whole_Process'], 'S2_Saturation/1', 'out_Saturation_2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation', 'out_Saturation_2', ME.message);
end
try
    add_line([model '/Whole_Process'], 'in_L2Int_1/1', 'S2_Saturation/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_L2Int_1', 'S2_Saturation', ME.message);
end
try
    add_line([model '/Whole_Process'], 'in_P100_Value_2/1', 'S2_Saturation2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_P100_Value_2', 'S2_Saturation2', ME.message);
end
try
    add_line([model '/Whole_Process'], 'in_Integrator_3/1', 'S2_Saturation3/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Integrator_3', 'S2_Saturation3', ME.message);
end
try
    add_line([model '/Whole_Process'], 'in_Saturation_p_4/1', 'S2_Saturation4/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Saturation_p_4', 'S2_Saturation4', ME.message);
end
try
    add_line([model '/Whole_Process'], 'in_Gain1_a_5/1', 'S2_Saturation5/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Gain1_a_5', 'S2_Saturation5', ME.message);
end
try
    add_line([model '/Whole_Process'], 'in_F200_Value_6/1', 'S2_Saturation6/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_F200_Value_6', 'S2_Saturation6', ME.message);
end
try
    add_line([model '/Whole_Process'], 'S2_Saturation6/1', 'out_Saturation6_3/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation6', 'out_Saturation6_3', ME.message);
end
try
    add_line([model '/Whole_Process'], 'S2_Saturation3/1', 'out_Saturation3_4/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation3', 'out_Saturation3_4', ME.message);
end
try
    add_line([model '/Whole_Process'], 'S2_Saturation4/1', 'out_Saturation4_5/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation4', 'out_Saturation4_5', ME.message);
end
try
    add_line([model '/Whole_Process'], 'S2_Saturation2/1', 'out_Saturation2_6/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation2', 'out_Saturation2_6', ME.message);
end
try
    add_line([model '/Whole_Process'], 'S2_Saturation3/1', 'out_Saturation3_7/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation3', 'out_Saturation3_7', ME.message);
end
try
    add_line([model '/Whole_Process'], 'S2_Saturation5/1', 'out_Saturation5_8/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation5', 'out_Saturation5_8', ME.message);
end
try
    add_line([model '/Condenser'], 'S4_Gain1/1', 'out_Gain1_a_1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S4_Gain1', 'out_Gain1_a_1', ME.message);
end
try
    add_line([model '/Condenser'], 'S4_Sum/1', 'S4_Gain/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S4_Sum', 'S4_Gain', ME.message);
end
try
    add_line([model '/Condenser'], 'S4_Product1/1', 'S4_Gain1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S4_Product1', 'S4_Gain1', ME.message);
end
try
    add_line([model '/Condenser'], 'in_Constant_Value_c_1/1', 'S4_Product/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Constant_Value_c_1', 'S4_Product', ME.message);
end
try
    add_line([model '/Condenser'], 'in_Constant1_Value_h_2/1', 'S4_Product/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Constant1_Value_h_2', 'S4_Product', ME.message);
end
try
    add_line([model '/Condenser'], 'in_Saturation6_3/1', 'S4_Product/3', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Saturation6_3', 'S4_Product', ME.message);
end
try
    add_line([model '/Condenser'], 'S4_Gain/1', 'S4_Product1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S4_Gain', 'S4_Product1', ME.message);
end
try
    add_line([model '/Condenser'], 'S4_Sum1/1', 'S4_Product1/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S4_Sum1', 'S4_Product1', ME.message);
end
try
    add_line([model '/Condenser'], 'in_Sum3_4/1', 'S4_Sum/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Sum3_4', 'S4_Sum', ME.message);
end
try
    add_line([model '/Condenser'], 'in_T200_Value_5/1', 'S4_Sum/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_T200_Value_5', 'S4_Sum', ME.message);
end
try
    add_line([model '/Condenser'], 'in_Constant2_Value_6/1', 'S4_Sum1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Constant2_Value_6', 'S4_Sum1', ME.message);
end
try
    add_line([model '/Condenser'], 'S4_Product/1', 'S4_Sum1/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S4_Product', 'S4_Sum1', ME.message);
end
try
    add_line([model '/Separator'], 'S5_L2Int/1', 'out_L2Int_1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S5_L2Int', 'out_L2Int_1', ME.message);
end
try
    add_line([model '/Separator'], 'S5_Sum/1', 'S5_Gain/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S5_Sum', 'S5_Gain', ME.message);
end
try
    add_line([model '/Separator'], 'S5_Gain/1', 'S5_L2Int/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S5_Gain', 'S5_L2Int', ME.message);
end
try
    add_line([model '/Separator'], 'in_F1_Step_1/1', 'S5_Sum/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_F1_Step_1', 'S5_Sum', ME.message);
end
try
    add_line([model '/Separator'], 'in_Saturation3_2/1', 'S5_Sum/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Saturation3_2', 'S5_Sum', ME.message);
end
try
    add_line([model '/Separator'], 'in_Saturation4_3/1', 'S5_Sum/3', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Saturation4_3', 'S5_Sum', ME.message);
end
try
    add_line([model '/Steamjacket'], 'in_Saturation2_1/1', 'S6_Gain/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Saturation2_1', 'S6_Gain', ME.message);
end
try
    add_line([model '/Steamjacket'], 'S6_Sum1/1', 'S6_Gain1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S6_Sum1', 'S6_Gain1', ME.message);
end
try
    add_line([model '/Steamjacket'], 'S6_Gain1/1', 'S6_Product/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S6_Gain1', 'S6_Product', ME.message);
end
try
    add_line([model '/Steamjacket'], 'S6_Sum2/1', 'S6_Product/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S6_Sum2', 'S6_Product', ME.message);
end
try
    add_line([model '/Steamjacket'], 'in_Constant1_Value_2/1', 'S6_Sum/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Constant1_Value_2', 'S6_Sum', ME.message);
end
try
    add_line([model '/Steamjacket'], 'S6_Gain/1', 'S6_Sum/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S6_Gain', 'S6_Sum', ME.message);
end
try
    add_line([model '/Steamjacket'], 'in_F1_Step_3/1', 'S6_Sum1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_F1_Step_3', 'S6_Sum1', ME.message);
end
try
    add_line([model '/Steamjacket'], 'in_F3_Value_4/1', 'S6_Sum1/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_F3_Value_4', 'S6_Sum1', ME.message);
end
try
    add_line([model '/Steamjacket'], 'S6_Sum/1', 'S6_Sum2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S6_Sum', 'S6_Sum2', ME.message);
end
try
    add_line([model '/Steamjacket'], 'in_Sum2_5/1', 'S6_Sum2/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Sum2_5', 'S6_Sum2', ME.message);
end
try
    add_line([model '/Steamjacket'], 'S6_Product/1', 'out_Product_1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S6_Product', 'out_Product_1', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Saturation/1', 'out_Saturation_p_1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Saturation', 'out_Saturation_p_1', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Sum3/1', 'out_Sum3_2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum3', 'out_Sum3_2', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Sum2/1', 'out_Sum2_3/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum2', 'out_Sum2_3', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Sum/1', 'S7_Gain/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum', 'S7_Gain', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Sum1/1', 'S7_Gain1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum1', 'S7_Gain1', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Saturation1/1', 'S7_Gain2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Saturation1', 'S7_Gain2', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_X2Int/1', 'S7_Gain3/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_X2Int', 'S7_Gain3', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Saturation1/1', 'S7_Gain4/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Saturation1', 'S7_Gain4', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Product2/1', 'S7_Gain5/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Product2', 'S7_Gain5', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Sum4/1', 'S7_Gain6/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum4', 'S7_Gain6', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Gain1/1', 'S7_P2Int/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain1', 'S7_P2Int', ME.message);
end
try
    add_line([model '/Evaporator'], 'in_F1_Step_1/1', 'S7_Product/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_F1_Step_1', 'S7_Product', ME.message);
end
try
    add_line([model '/Evaporator'], 'in_X1_Step_2/1', 'S7_Product/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_X1_Step_2', 'S7_Product', ME.message);
end
try
    add_line([model '/Evaporator'], 'in_Saturation3_3/1', 'S7_Product1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Saturation3_3', 'S7_Product1', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_X2Int/1', 'S7_Product1/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_X2Int', 'S7_Product1', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Sum5/1', 'S7_Product2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum5', 'S7_Product2', ME.message);
end
try
    add_line([model '/Evaporator'], 'in_F1_Step_4/1', 'S7_Product2/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_F1_Step_4', 'S7_Product2', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Gain6/1', 'S7_Saturation/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain6', 'S7_Saturation', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_P2Int/1', 'S7_Saturation1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_P2Int', 'S7_Saturation1', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Saturation/1', 'S7_Saturation2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Saturation', 'S7_Saturation2', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Product/1', 'S7_Sum/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Product', 'S7_Sum', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Product1/1', 'S7_Sum/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Product1', 'S7_Sum', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Saturation2/1', 'S7_Sum1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Saturation2', 'S7_Sum1', ME.message);
end
try
    add_line([model '/Evaporator'], 'in_Saturation5_5/1', 'S7_Sum1/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Saturation5_5', 'S7_Sum1', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Gain3/1', 'S7_Sum2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain3', 'S7_Sum2', ME.message);
end
try
    add_line([model '/Evaporator'], 'in_Constant_Value_6/1', 'S7_Sum2/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Constant_Value_6', 'S7_Sum2', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Gain2/1', 'S7_Sum2/3', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain2', 'S7_Sum2', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Gain4/1', 'S7_Sum3/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain4', 'S7_Sum3', ME.message);
end
try
    add_line([model '/Evaporator'], 'in_Constant1_Value_i_7/1', 'S7_Sum3/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Constant1_Value_i_7', 'S7_Sum3', ME.message);
end
try
    add_line([model '/Evaporator'], 'in_Product_8/1', 'S7_Sum4/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Product_8', 'S7_Sum4', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Gain5/1', 'S7_Sum4/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain5', 'S7_Sum4', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Sum2/1', 'S7_Sum5/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum2', 'S7_Sum5', ME.message);
end
try
    add_line([model '/Evaporator'], 'in_T1_Value_9/1', 'S7_Sum5/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_T1_Value_9', 'S7_Sum5', ME.message);
end
try
    add_line([model '/Evaporator'], 'S7_Gain/1', 'S7_X2Int/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain', 'S7_X2Int', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_F2_Value/1', 'out_F2_Value_1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_F2_Value', 'out_F2_Value_1', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_P100_Value/1', 'out_P100_Value_2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_P100_Value', 'out_P100_Value_2', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_F200_Value/1', 'out_F200_Value_3/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_F200_Value', 'out_F200_Value_3', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_Constant_Value_c/1', 'out_Constant_Value_c_4/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_Constant_Value_c', 'out_Constant_Value_c_4', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_Constant1_Value_h/1', 'out_Constant1_Value_h_5/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_Constant1_Value_h', 'out_Constant1_Value_h_5', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_T200_Value/1', 'out_T200_Value_6/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_T200_Value', 'out_T200_Value_6', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_Constant2_Value/1', 'out_Constant2_Value_7/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_Constant2_Value', 'out_Constant2_Value_7', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_Constant1_Value/1', 'out_Constant1_Value_8/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_Constant1_Value', 'out_Constant1_Value_8', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_F3_Value/1', 'out_F3_Value_9/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_F3_Value', 'out_F3_Value_9', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_Constant_Value/1', 'out_Constant_Value_10/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_Constant_Value', 'out_Constant_Value_10', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_Constant1_Value_i/1', 'out_Constant1_Value_i_11/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_Constant1_Value_i', 'out_Constant1_Value_i_11', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_T1_Value/1', 'out_T1_Value_12/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_T1_Value', 'out_T1_Value_12', ME.message);
end
% Connect top-level subsystem and interface signals.
try
    add_line(model, 'Whole_Process/1', 'L2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Whole_Process', 'L2', ME.message);
end
try
    add_line(model, 'Whole_Process/2', 'Root_Controller/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Whole_Process', 'Root_Controller', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/1', 'Root_Controller/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Root_Controller', ME.message);
end
try
    add_line(model, 'Separator/1', 'Whole_Process/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Separator', 'Whole_Process', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/2', 'Whole_Process/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Whole_Process', ME.message);
end
try
    add_line(model, 'Delay/1', 'Whole_Process/3', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Delay', 'Whole_Process', ME.message);
end
try
    add_line(model, 'Evaporator/1', 'Whole_Process/4', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Evaporator', 'Whole_Process', ME.message);
end
try
    add_line(model, 'Condenser/1', 'Whole_Process/5', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Condenser', 'Whole_Process', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/3', 'Whole_Process/6', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Whole_Process', ME.message);
end
try
    add_line(model, 'Root_Controller/1', 'Delay/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_Controller', 'Delay', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/4', 'Condenser/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Condenser', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/5', 'Condenser/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Condenser', ME.message);
end
try
    add_line(model, 'Whole_Process/3', 'Condenser/3', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Whole_Process', 'Condenser', ME.message);
end
try
    add_line(model, 'Evaporator/2', 'Condenser/4', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Evaporator', 'Condenser', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/6', 'Condenser/5', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Condenser', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/7', 'Condenser/6', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Condenser', ME.message);
end
try
    add_line(model, 'Root_Controller/2', 'Separator/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_Controller', 'Separator', ME.message);
end
try
    add_line(model, 'Whole_Process/4', 'Separator/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Whole_Process', 'Separator', ME.message);
end
try
    add_line(model, 'Whole_Process/5', 'Separator/3', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Whole_Process', 'Separator', ME.message);
end
try
    add_line(model, 'Whole_Process/6', 'Steamjacket/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Whole_Process', 'Steamjacket', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/8', 'Steamjacket/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Steamjacket', ME.message);
end
try
    add_line(model, 'Root_Controller/3', 'Steamjacket/3', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_Controller', 'Steamjacket', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/9', 'Steamjacket/4', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Steamjacket', ME.message);
end
try
    add_line(model, 'Evaporator/3', 'Steamjacket/5', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Evaporator', 'Steamjacket', ME.message);
end
try
    add_line(model, 'Root_Controller/4', 'Evaporator/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_Controller', 'Evaporator', ME.message);
end
try
    add_line(model, 'Root_Controller/5', 'Evaporator/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_Controller', 'Evaporator', ME.message);
end
try
    add_line(model, 'Whole_Process/7', 'Evaporator/3', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Whole_Process', 'Evaporator', ME.message);
end
try
    add_line(model, 'Root_Controller/6', 'Evaporator/4', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_Controller', 'Evaporator', ME.message);
end
try
    add_line(model, 'Whole_Process/8', 'Evaporator/5', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Whole_Process', 'Evaporator', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/10', 'Evaporator/6', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Evaporator', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/11', 'Evaporator/7', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Evaporator', ME.message);
end
try
    add_line(model, 'Steamjacket/1', 'Evaporator/8', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Steamjacket', 'Evaporator', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/12', 'Evaporator/9', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Evaporator', ME.message);
end

% Validate expected top-level block and signal-line counts.
fprintf('[validation] Checking top-level block and signal-line counts.\n');
actualBlockCount = numel(find_system(model, 'Type', 'Block'));
actualLineCount = numel(find_system(model, 'FindAll', 'on', 'Type', 'line'));
if actualBlockCount ~= expectedBlockCount
    warning('Expected %d blocks, but found %d.', expectedBlockCount, actualBlockCount);
end
if actualLineCount ~= expectedLineCount
    warning('Expected %d signal lines, but found %d.', expectedLineCount, actualLineCount);
end

% Add reconstruction notes and unmapped-code annotations.
try
    ann = Simulink.Annotation(model, 'Layout strategy: Complex subsystem preferred. A compact top-level diagram uses finer-grained subsystems for controller, delay, process, condenser, separator, steamjacket, evaporator, and inferred parameter helpers.');
    ann.Position = [30 75 520 110];
catch ME
    warning('Could not add annotation: %s', ME.message);
end
try
    ann = Simulink.Annotation(model, 'This model is inferred from generated C code. Simulink Coder output is not lossless; names, hierarchy, masks, sample times, solver settings, and annotations may differ from the original model.');
    ann.Position = [30 120 520 155];
catch ME
    warning('Could not add annotation: %s', ME.message);
end

fprintf('[save] Saving model to %s.slx.\n', model);
save_system(model);
fprintf('[summary] Blocks: %d; signal lines: %d; model: %s; layout: %s.\n', actualBlockCount, actualLineCount, model, layoutStrategy);
