% Auto-generated by the Python Simulink C reconstruction tool.
% The result is an approximate visualization and starting point.
% Generated from Simulink Coder C, which is not a lossless model format.
% Original model inferred from C: process_PIConstrained
% Layout strategy: Left-to-right signal flow.
% Layout note: Blocks are arranged by dependency depth so upstream sources stay left and downstream outputs move right.
% Inferred facts are represented as blocks, lines, and annotations.

model = 'reconstructed_model_layout2_left_to_right_signal_flow';
originalModelName = 'process_PIConstrained';
layoutStrategy = 'Left-to-right signal flow';
layoutDescription = 'Blocks are arranged by dependency depth so upstream sources stay left and downstream outputs move right.';
expectedBlockCount = 67;
expectedLineCount = 77;
directMappedBlockCount = 55;
inferredBlockCount = 12;
fprintf('[parsing] Replaying reconstruction facts parsed from Simulink Coder output for %s.\n', originalModelName);
fprintf('[block creation] Creating %d blocks: %d directly mapped and %d inferred helper blocks.\n', expectedBlockCount, directMappedBlockCount, inferredBlockCount);
fprintf('[inferred-block creation] Inferred block names include the word inferred.\n');
fprintf('[layout] %s: %s\n', layoutStrategy, layoutDescription);
if bdIsLoaded(model)
    close_system(model, 0);
end
if exist([model '.slx'], 'file')
    delete([model '.slx']);
end
new_system(model);
open_system(model);

% Add blocks. Inferred helper blocks include the word inferred in the name.
% Outport: L2
% C expression: process_PIConstrained_B.Saturation
add_block('simulink/Sinks/Out1', [model '/L2'], 'MakeNameUnique', 'off');
set_param([model '/L2'], 'Position', [5740 40 5810 72]);
set_param([model '/L2'], 'Port', '1');

% Integrator: S5_L2Int
% Source trace: <S5>/L2Int (certain)
% C expression: process_PIConstrained_B.Gain_g
add_block('simulink/Continuous/Integrator', [model '/S5_L2Int'], 'MakeNameUnique', 'off');
set_param([model '/S5_L2Int'], 'Position', [5170 40 5300 100]);
set_param([model '/S5_L2Int'], 'InitialCondition', '1.0');

% Saturation: S2_Saturation
% Source trace: <S2>/Saturation (certain)
% C expression: (process_PIConstrained_P.Saturation_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/S2_Saturation'], 'MakeNameUnique', 'off');
set_param([model '/S2_Saturation'], 'Position', [5360 40 5470 90]);
set_param([model '/S2_Saturation'], 'LowerLimit', '0.0');
set_param([model '/S2_Saturation'], 'UpperLimit', '2.0');

% Step: Root_F1_Step
% Source trace: <Root>/F1_Step (certain)
% C expression: process_PIConstrained_P.F1_Step_Y0
add_block('simulink/Sources/Step', [model '/Root_F1_Step'], 'MakeNameUnique', 'off');
set_param([model '/Root_F1_Step'], 'Position', [40 40 144 86]);
set_param([model '/Root_F1_Step'], 'Time', '200.0');
set_param([model '/Root_F1_Step'], 'Before', '10.0');
set_param([model '/Root_F1_Step'], 'After', '10.0');

% Sum: S6_Sum1
% Source trace: <S6>/Sum1 (certain)
% C expression: process_PIConstrained_B.F1_Step + process_PIConstrained_P.F3_Value
add_block('simulink/Math Operations/Sum', [model '/S6_Sum1'], 'MakeNameUnique', 'off');
set_param([model '/S6_Sum1'], 'Position', [230 210 300 260]);
set_param([model '/S6_Sum1'], 'Inputs', '++');

% Gain: S6_Gain1
% Source trace: <S6>/Gain1 (certain)
% C expression: process_PIConstrained_P.Gain1_Gain * process_PIConstrained_B.Sum1
add_block('simulink/Math Operations/Gain', [model '/S6_Gain1'], 'MakeNameUnique', 'off');
set_param([model '/S6_Gain1'], 'Position', [420 295 500 341]);
set_param([model '/S6_Gain1'], 'Gain', '0.16');

% Saturation: S2_Saturation2
% Source trace: <S2>/Saturation2 (certain)
% C expression: (process_PIConstrained_P.Saturation2_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/S2_Saturation2'], 'MakeNameUnique', 'off');
set_param([model '/S2_Saturation2'], 'Position', [230 40 340 90]);
set_param([model '/S2_Saturation2'], 'LowerLimit', '0.0');
set_param([model '/S2_Saturation2'], 'UpperLimit', '400.0');

% Gain: S6_Gain
% Source trace: <S6>/Gain (certain)
% C expression: process_PIConstrained_P.Gain_Gain * process_PIConstrained_B.Saturation2
add_block('simulink/Math Operations/Gain', [model '/S6_Gain'], 'MakeNameUnique', 'off');
set_param([model '/S6_Gain'], 'Position', [420 210 500 256]);
set_param([model '/S6_Gain'], 'Gain', '0.1538');

% Sum: S6_Sum
% Source trace: <S6>/Sum (certain)
% C expression: process_PIConstrained_P.Constant1_Value + process_PIConstrained_B.Gain
add_block('simulink/Math Operations/Sum', [model '/S6_Sum'], 'MakeNameUnique', 'off');
set_param([model '/S6_Sum'], 'Position', [610 210 680 260]);
set_param([model '/S6_Sum'], 'Inputs', '++');

% Integrator: S7_X2Int
% Source trace: <S7>/X2Int (certain)
% C expression: process_PIConstrained_B.Gain_a
add_block('simulink/Continuous/Integrator', [model '/S7_X2Int'], 'MakeNameUnique', 'off');
set_param([model '/S7_X2Int'], 'Position', [2890 40 3020 100]);
set_param([model '/S7_X2Int'], 'InitialCondition', '25.0');

% Gain: S7_Gain3
% Source trace: <S7>/Gain3 (certain)
% C expression: process_PIConstrained_P.Gain3_Gain * process_PIConstrained_B.X2Int
add_block('simulink/Math Operations/Gain', [model '/S7_Gain3'], 'MakeNameUnique', 'off');
set_param([model '/S7_Gain3'], 'Position', [3080 40 3160 86]);
set_param([model '/S7_Gain3'], 'Gain', '0.3126');

% Integrator: S7_P2Int
% Source trace: <S7>/P2Int (certain)
% C expression: process_PIConstrained_B.Gain1_f
add_block('simulink/Continuous/Integrator', [model '/S7_P2Int'], 'MakeNameUnique', 'off');
set_param([model '/S7_P2Int'], 'Position', [2130 125 2260 185]);
set_param([model '/S7_P2Int'], 'InitialCondition', '50.5');

% Saturation: S7_Saturation1
% Source trace: <S7>/Saturation1 (certain)
% C expression: (process_PIConstrained_P.Saturation1_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/S7_Saturation1'], 'MakeNameUnique', 'off');
set_param([model '/S7_Saturation1'], 'Position', [2320 125 2430 175]);
set_param([model '/S7_Saturation1'], 'LowerLimit', '0.0');
set_param([model '/S7_Saturation1'], 'UpperLimit', '100.0');

% Gain: S7_Gain2
% Source trace: <S7>/Gain2 (certain)
% C expression: process_PIConstrained_P.Gain2_Gain * process_PIConstrained_B.Saturation1
add_block('simulink/Math Operations/Gain', [model '/S7_Gain2'], 'MakeNameUnique', 'off');
set_param([model '/S7_Gain2'], 'Position', [2510 40 2590 86]);
set_param([model '/S7_Gain2'], 'Gain', '0.5616');

% Sum: S7_Sum2
% Source trace: <S7>/Sum2 (certain)
% C expression: (process_PIConstrained_B.Gain3 + process_PIConstrained_P.Constant_Value) + process_PIConstrained_B.Gain2
add_block('simulink/Math Operations/Sum', [model '/S7_Sum2'], 'MakeNameUnique', 'off');
set_param([model '/S7_Sum2'], 'Position', [3270 40 3340 90]);
set_param([model '/S7_Sum2'], 'Inputs', '+++');

% Sum: S6_Sum2
% Source trace: <S6>/Sum2 (certain)
% C expression: process_PIConstrained_B.Sum - process_PIConstrained_B.Sum2
add_block('simulink/Math Operations/Sum', [model '/S6_Sum2'], 'MakeNameUnique', 'off');
set_param([model '/S6_Sum2'], 'Position', [3460 40 3530 90]);
set_param([model '/S6_Sum2'], 'Inputs', '+-');

% Product: S6_Product
% Source trace: <S6>/Product (certain)
% C expression: process_PIConstrained_B.Gain1 * process_PIConstrained_B.Sum2_o
add_block('simulink/Math Operations/Product', [model '/S6_Product'], 'MakeNameUnique', 'off');
set_param([model '/S6_Product'], 'Position', [3650 40 3720 90]);
set_param([model '/S6_Product'], 'Inputs', '**');

% Sum: S7_Sum5
% Source trace: <S7>/Sum5 (certain)
% C expression: process_PIConstrained_B.Sum2 - process_PIConstrained_P.T1_Value
add_block('simulink/Math Operations/Sum', [model '/S7_Sum5'], 'MakeNameUnique', 'off');
set_param([model '/S7_Sum5'], 'Position', [3460 125 3530 175]);
set_param([model '/S7_Sum5'], 'Inputs', '+-');

% Product: S7_Product2
% Source trace: <S7>/Product2 (certain)
% C expression: process_PIConstrained_B.Sum5 * process_PIConstrained_B.F1_Step
add_block('simulink/Math Operations/Product', [model '/S7_Product2'], 'MakeNameUnique', 'off');
set_param([model '/S7_Product2'], 'Position', [3650 125 3720 175]);
set_param([model '/S7_Product2'], 'Inputs', '**');

% Gain: S7_Gain5
% Source trace: <S7>/Gain5 (certain)
% C expression: process_PIConstrained_P.Gain5_Gain * process_PIConstrained_B.Product2
add_block('simulink/Math Operations/Gain', [model '/S7_Gain5'], 'MakeNameUnique', 'off');
set_param([model '/S7_Gain5'], 'Position', [3840 40 3920 86]);
set_param([model '/S7_Gain5'], 'Gain', '0.07');

% Sum: S7_Sum4
% Source trace: <S7>/Sum4 (certain)
% C expression: process_PIConstrained_B.Product - process_PIConstrained_B.Gain5
add_block('simulink/Math Operations/Sum', [model '/S7_Sum4'], 'MakeNameUnique', 'off');
set_param([model '/S7_Sum4'], 'Position', [4030 40 4100 90]);
set_param([model '/S7_Sum4'], 'Inputs', '+-');

% Gain: S7_Gain6
% Source trace: <S7>/Gain6 (certain)
% C expression: process_PIConstrained_P.Gain6_Gain * process_PIConstrained_B.Sum4
add_block('simulink/Math Operations/Gain', [model '/S7_Gain6'], 'MakeNameUnique', 'off');
set_param([model '/S7_Gain6'], 'Position', [4220 40 4300 86]);
set_param([model '/S7_Gain6'], 'Gain', '0.025974025974025976');

% Saturation: S7_Saturation
% Source trace: <S7>/Saturation (certain)
% C expression: (process_PIConstrained_P.Saturation_UpperSat_p)
add_block('simulink/Discontinuities/Saturation', [model '/S7_Saturation'], 'MakeNameUnique', 'off');
set_param([model '/S7_Saturation'], 'Position', [4410 40 4520 90]);
set_param([model '/S7_Saturation'], 'LowerLimit', '0.0');
set_param([model '/S7_Saturation'], 'UpperLimit', '16.0');

% Saturation: S2_Saturation4
% Source trace: <S2>/Saturation4 (certain)
% C expression: (process_PIConstrained_P.Saturation4_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/S2_Saturation4'], 'MakeNameUnique', 'off');
set_param([model '/S2_Saturation4'], 'Position', [4600 40 4710 90]);
set_param([model '/S2_Saturation4'], 'LowerLimit', '0.0');
set_param([model '/S2_Saturation4'], 'UpperLimit', '16.0');

% Integrator: Root_FeedbackInt
% Source trace: <Root>/FeedbackInt (certain)
% C expression: process_PIConstrained_B.Ti
add_block('simulink/Continuous/Integrator', [model '/Root_FeedbackInt'], 'MakeNameUnique', 'off');
set_param([model '/Root_FeedbackInt'], 'Position', [990 40 1120 100]);
set_param([model '/Root_FeedbackInt'], 'InitialCondition', '0.0');

% Step: Root_L2_Set_Point
% Source trace: <Root>/L2 Set Point (certain)
% C expression: process_PIConstrained_P.L2SetPoint_Y0
add_block('simulink/Sources/Step', [model '/Root_L2_Set_Point'], 'MakeNameUnique', 'off');
set_param([model '/Root_L2_Set_Point'], 'Position', [40 125 179 171]);
set_param([model '/Root_L2_Set_Point'], 'Time', '200.0');
set_param([model '/Root_L2_Set_Point'], 'Before', '1.0');
set_param([model '/Root_L2_Set_Point'], 'After', '1.0');

% Sum: Root_Sum
% Source trace: <Root>/Sum (certain)
% C expression: process_PIConstrained_B.L2SetPoint - process_PIConstrained_B.Saturation
add_block('simulink/Math Operations/Sum', [model '/Root_Sum'], 'MakeNameUnique', 'off');
set_param([model '/Root_Sum'], 'Position', [420 40 490 90]);
set_param([model '/Root_Sum'], 'Inputs', '+-');

% Gain: S1_Slider_Gain
% Source trace: <S1>/Slider Gain (certain)
% C expression: process_PIConstrained_P.L2ProportionalGain_gain * process_PIConstrained_B.Sum_k
add_block('simulink/Math Operations/Gain', [model '/S1_Slider_Gain'], 'MakeNameUnique', 'off');
set_param([model '/S1_Slider_Gain'], 'Position', [610 40 728 86]);
set_param([model '/S1_Slider_Gain'], 'Gain', '-14.18');

% Sum: Root_Sum2
% Source trace: <Root>/Sum2 (certain)
% C expression: process_PIConstrained_B.SliderGain + process_PIConstrained_B.FeedbackInt
add_block('simulink/Math Operations/Sum', [model '/Root_Sum2'], 'MakeNameUnique', 'off');
set_param([model '/Root_Sum2'], 'Position', [1180 40 1250 90]);
set_param([model '/Root_Sum2'], 'Inputs', '++');

% Sum: Root_Sum1
% Source trace: <Root>/Sum1 (certain)
% C expression: process_PIConstrained_P.F2_Value + process_PIConstrained_B.Sum2_oi
add_block('simulink/Math Operations/Sum', [model '/Root_Sum1'], 'MakeNameUnique', 'off');
set_param([model '/Root_Sum1'], 'Position', [1370 40 1440 90]);
set_param([model '/Root_Sum1'], 'Inputs', '++');

% Gain: Root_Ti
% Source trace: <Root>/Ti (certain)
% C expression: process_PIConstrained_P.Ti_Gain * process_PIConstrained_B.SliderGain
add_block('simulink/Math Operations/Gain', [model '/Root_Ti'], 'MakeNameUnique', 'off');
set_param([model '/Root_Ti'], 'Position', [800 40 880 86]);
set_param([model '/Root_Ti'], 'Gain', '0.052826201796090863');

% Gain: S7_Gain4
% Source trace: <S7>/Gain4 (certain)
% C expression: process_PIConstrained_P.Gain4_Gain * process_PIConstrained_B.Saturation1
add_block('simulink/Math Operations/Gain', [model '/S7_Gain4'], 'MakeNameUnique', 'off');
set_param([model '/S7_Gain4'], 'Position', [420 380 500 426]);
set_param([model '/S7_Gain4'], 'Gain', '0.507');

% Sum: S7_Sum3
% Source trace: <S7>/Sum3 (certain)
% C expression: process_PIConstrained_B.Gain4 + process_PIConstrained_P.Constant1_Value_i
add_block('simulink/Math Operations/Sum', [model '/S7_Sum3'], 'MakeNameUnique', 'off');
set_param([model '/S7_Sum3'], 'Position', [610 295 680 345]);
set_param([model '/S7_Sum3'], 'Inputs', '++');

% Sum: S4_Sum
% Source trace: <S4>/Sum (certain)
% C expression: process_PIConstrained_B.Sum3 - process_PIConstrained_P.T200_Value
add_block('simulink/Math Operations/Sum', [model '/S4_Sum'], 'MakeNameUnique', 'off');
set_param([model '/S4_Sum'], 'Position', [800 125 870 175]);
set_param([model '/S4_Sum'], 'Inputs', '+-');

% Gain: S4_Gain
% Source trace: <S4>/Gain (certain)
% C expression: process_PIConstrained_P.Gain_Gain_h * process_PIConstrained_B.Sum_d
add_block('simulink/Math Operations/Gain', [model '/S4_Gain'], 'MakeNameUnique', 'off');
set_param([model '/S4_Gain'], 'Position', [990 125 1070 171]);
set_param([model '/S4_Gain'], 'Gain', '6.84');

% Saturation: S2_Saturation6
% Source trace: <S2>/Saturation6 (certain)
% C expression: (process_PIConstrained_P.Saturation6_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/S2_Saturation6'], 'MakeNameUnique', 'off');
set_param([model '/S2_Saturation6'], 'Position', [230 125 340 175]);
set_param([model '/S2_Saturation6'], 'LowerLimit', '0.0');
set_param([model '/S2_Saturation6'], 'UpperLimit', '416.0');

% Product: S4_Product
% Source trace: <S4>/Product (certain)
% C expression: process_PIConstrained_P.Constant_Value_c / process_PIConstrained_P.Constant1_Value_h / process_PIConstrained_B.Saturation6
add_block('simulink/Math Operations/Product', [model '/S4_Product'], 'MakeNameUnique', 'off');
set_param([model '/S4_Product'], 'Position', [420 125 490 175]);
set_param([model '/S4_Product'], 'Inputs', '*//');

% Sum: S4_Sum1
% Source trace: <S4>/Sum1 (certain)
% C expression: process_PIConstrained_P.Constant2_Value + process_PIConstrained_B.Product_k
add_block('simulink/Math Operations/Sum', [model '/S4_Sum1'], 'MakeNameUnique', 'off');
set_param([model '/S4_Sum1'], 'Position', [610 125 680 175]);
set_param([model '/S4_Sum1'], 'Inputs', '++');

% Product: S4_Product1
% Source trace: <S4>/Product1 (certain)
% C expression: process_PIConstrained_B.Gain_c / process_PIConstrained_B.Sum1_h
add_block('simulink/Math Operations/Product', [model '/S4_Product1'], 'MakeNameUnique', 'off');
set_param([model '/S4_Product1'], 'Position', [1180 125 1250 175]);
set_param([model '/S4_Product1'], 'Inputs', '*/');

% Gain: S4_Gain1
% Source trace: <S4>/Gain1 (certain)
% C expression: process_PIConstrained_P.Gain1_Gain_l * process_PIConstrained_B.Q200
add_block('simulink/Math Operations/Gain', [model '/S4_Gain1'], 'MakeNameUnique', 'off');
set_param([model '/S4_Gain1'], 'Position', [1370 125 1450 171]);
set_param([model '/S4_Gain1'], 'Gain', '0.025974025974025976');

% Integrator: S3_Integrator
% Source trace: <S3>/Integrator (certain)
% C expression: process_PIConstrained_B.Gain_b
add_block('simulink/Continuous/Integrator', [model '/S3_Integrator'], 'MakeNameUnique', 'off');
set_param([model '/S3_Integrator'], 'Position', [1940 40 2070 100]);
set_param([model '/S3_Integrator'], 'InitialCondition', '0.0');

% Saturation: S2_Saturation3
% Source trace: <S2>/Saturation3 (certain)
% C expression: (process_PIConstrained_P.Saturation3_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/S2_Saturation3'], 'MakeNameUnique', 'off');
set_param([model '/S2_Saturation3'], 'Position', [2130 40 2240 90]);
set_param([model '/S2_Saturation3'], 'LowerLimit', '0.0');
set_param([model '/S2_Saturation3'], 'UpperLimit', '4.0');

% Saturation: S2_Saturation5
% Source trace: <S2>/Saturation5 (certain)
% C expression: (process_PIConstrained_P.Saturation5_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/S2_Saturation5'], 'MakeNameUnique', 'off');
set_param([model '/S2_Saturation5'], 'Position', [1560 40 1670 90]);
set_param([model '/S2_Saturation5'], 'LowerLimit', '0.0');
set_param([model '/S2_Saturation5'], 'UpperLimit', '16.0');

% Sum: S5_Sum
% Source trace: <S5>/Sum (certain)
% C expression: (process_PIConstrained_B.F1_Step - process_PIConstrained_B.Saturation3) - process_PIConstrained_B.Saturation4
add_block('simulink/Math Operations/Sum', [model '/S5_Sum'], 'MakeNameUnique', 'off');
set_param([model '/S5_Sum'], 'Position', [4790 40 4860 90]);
set_param([model '/S5_Sum'], 'Inputs', '+--');

% Gain: S5_Gain
% Source trace: <S5>/Gain (certain)
% C expression: process_PIConstrained_P.Gain_Gain_k * process_PIConstrained_B.Sum_m
add_block('simulink/Math Operations/Gain', [model '/S5_Gain'], 'MakeNameUnique', 'off');
set_param([model '/S5_Gain'], 'Position', [4980 40 5060 86]);
set_param([model '/S5_Gain'], 'Gain', '0.05');

% Step: Root_X1_Step
% Source trace: <Root>/X1_Step (certain)
% C expression: process_PIConstrained_P.X1_Step_Y0
add_block('simulink/Sources/Step', [model '/Root_X1_Step'], 'MakeNameUnique', 'off');
set_param([model '/Root_X1_Step'], 'Position', [40 210 144 256]);
set_param([model '/Root_X1_Step'], 'Time', '200.0');
set_param([model '/Root_X1_Step'], 'Before', '5.0');
set_param([model '/Root_X1_Step'], 'After', '35.0');

% Product: S7_Product
% Source trace: <S7>/Product (certain)
% C expression: process_PIConstrained_B.F1_Step * process_PIConstrained_B.X1_Step
add_block('simulink/Math Operations/Product', [model '/S7_Product'], 'MakeNameUnique', 'off');
set_param([model '/S7_Product'], 'Position', [230 295 300 345]);
set_param([model '/S7_Product'], 'Inputs', '**');

% Product: S7_Product1
% Source trace: <S7>/Product1 (certain)
% C expression: process_PIConstrained_B.Saturation3 * process_PIConstrained_B.X2Int
add_block('simulink/Math Operations/Product', [model '/S7_Product1'], 'MakeNameUnique', 'off');
set_param([model '/S7_Product1'], 'Position', [2320 40 2390 90]);
set_param([model '/S7_Product1'], 'Inputs', '**');

% Sum: S7_Sum
% Source trace: <S7>/Sum (certain)
% C expression: process_PIConstrained_B.Product_c - process_PIConstrained_B.Product1
add_block('simulink/Math Operations/Sum', [model '/S7_Sum'], 'MakeNameUnique', 'off');
set_param([model '/S7_Sum'], 'Position', [2510 125 2580 175]);
set_param([model '/S7_Sum'], 'Inputs', '+-');

% Gain: S7_Gain
% Source trace: <S7>/Gain (certain)
% C expression: process_PIConstrained_P.Gain_Gain_n * process_PIConstrained_B.Sum_i
add_block('simulink/Math Operations/Gain', [model '/S7_Gain'], 'MakeNameUnique', 'off');
set_param([model '/S7_Gain'], 'Position', [2700 40 2780 86]);
set_param([model '/S7_Gain'], 'Gain', '0.05');

% Saturation: S7_Saturation2
% Source trace: <S7>/Saturation2 (certain)
% C expression: (process_PIConstrained_P.Saturation2_UpperSat_l)
add_block('simulink/Discontinuities/Saturation', [model '/S7_Saturation2'], 'MakeNameUnique', 'off');
set_param([model '/S7_Saturation2'], 'Position', [420 465 530 515]);
set_param([model '/S7_Saturation2'], 'LowerLimit', '0.0');
set_param([model '/S7_Saturation2'], 'UpperLimit', '16.0');

% Sum: S7_Sum1
% Source trace: <S7>/Sum1 (certain)
% C expression: process_PIConstrained_B.Saturation2_e - process_PIConstrained_B.Saturation5
add_block('simulink/Math Operations/Sum', [model '/S7_Sum1'], 'MakeNameUnique', 'off');
set_param([model '/S7_Sum1'], 'Position', [1750 125 1820 175]);
set_param([model '/S7_Sum1'], 'Inputs', '+-');

% Gain: S7_Gain1
% Source trace: <S7>/Gain1 (certain)
% C expression: process_PIConstrained_P.Gain1_Gain_m * process_PIConstrained_B.Sum1_e
add_block('simulink/Math Operations/Gain', [model '/S7_Gain1'], 'MakeNameUnique', 'off');
set_param([model '/S7_Gain1'], 'Position', [1940 125 2020 171]);
set_param([model '/S7_Gain1'], 'Gain', '0.25');

% Sum: S3_Sum
% Source trace: <S3>/Sum (certain)
% C expression: process_PIConstrained_B.Sum1_g - process_PIConstrained_B.Integrator
add_block('simulink/Math Operations/Sum', [model '/S3_Sum'], 'MakeNameUnique', 'off');
set_param([model '/S3_Sum'], 'Position', [1560 125 1630 175]);
set_param([model '/S3_Sum'], 'Inputs', '+-');

% Gain: S3_Gain
% Source trace: <S3>/Gain (certain)
% C expression: process_PIConstrained_P.Gain_Gain_hu * process_PIConstrained_B.Sum_iw
add_block('simulink/Math Operations/Gain', [model '/S3_Gain'], 'MakeNameUnique', 'off');
set_param([model '/S3_Gain'], 'Position', [1750 40 1830 86]);
set_param([model '/S3_Gain'], 'Gain', '0.83333333333333337');

% Constant: inferred_Const_F3_Value
% Source trace: <Root>/F3 (inferred)
add_block('simulink/Sources/Constant', [model '/inferred_Const_F3_Value'], 'MakeNameUnique', 'off');
set_param([model '/inferred_Const_F3_Value'], 'Position', [40 975 190 1021]);
set_param([model '/inferred_Const_F3_Value'], 'Value', '50.0');

% Constant: inferred_Const_P100_Value
% Source trace: <Root>/P100 (inferred)
add_block('simulink/Sources/Constant', [model '/inferred_Const_P100_Value'], 'MakeNameUnique', 'off');
set_param([model '/inferred_Const_P100_Value'], 'Position', [40 1060 190 1106]);
set_param([model '/inferred_Const_P100_Value'], 'Value', '194.7');

% Constant: inferred_Const_Constant1_Value
% Source trace: <S6>/Constant1 (inferred)
add_block('simulink/Sources/Constant', [model '/inferred_Const_Constant1_Value'], 'MakeNameUnique', 'off');
set_param([model '/inferred_Const_Constant1_Value'], 'Position', [40 295 190 341]);
set_param([model '/inferred_Const_Constant1_Value'], 'Value', '90.0');

% Constant: inferred_Const_Constant_Value
% Source trace: <S7>/Constant (inferred)
add_block('simulink/Sources/Constant', [model '/inferred_Const_Constant_Value'], 'MakeNameUnique', 'off');
set_param([model '/inferred_Const_Constant_Value'], 'Position', [40 635 190 681]);
set_param([model '/inferred_Const_Constant_Value'], 'Value', '48.43');

% Constant: inferred_Const_T1_Value
% Source trace: <Root>/T1 (inferred)
add_block('simulink/Sources/Constant', [model '/inferred_Const_T1_Value'], 'MakeNameUnique', 'off');
set_param([model '/inferred_Const_T1_Value'], 'Position', [40 1145 190 1191]);
set_param([model '/inferred_Const_T1_Value'], 'Value', '40.0');

% Constant: inferred_Const_F2_Value
% Source trace: <Root>/F2 (inferred)
add_block('simulink/Sources/Constant', [model '/inferred_Const_F2_Value'], 'MakeNameUnique', 'off');
set_param([model '/inferred_Const_F2_Value'], 'Position', [40 890 190 936]);
set_param([model '/inferred_Const_F2_Value'], 'Value', '2.0');

% Constant: inferred_Const_Constant1_Value_i
% Source trace: <S7>/Constant1 (inferred)
add_block('simulink/Sources/Constant', [model '/inferred_Const_Constant1_Value_i'], 'MakeNameUnique', 'off');
set_param([model '/inferred_Const_Constant1_Value_i'], 'Position', [40 465 190 511]);
set_param([model '/inferred_Const_Constant1_Value_i'], 'Value', '55.0');

% Constant: inferred_Const_T200_Value
% Source trace: <Root>/T200 (inferred)
add_block('simulink/Sources/Constant', [model '/inferred_Const_T200_Value'], 'MakeNameUnique', 'off');
set_param([model '/inferred_Const_T200_Value'], 'Position', [40 1230 190 1276]);
set_param([model '/inferred_Const_T200_Value'], 'Value', '25.0');

% Constant: inferred_Const_F200_Value
% Source trace: <Root>/F200 (inferred)
add_block('simulink/Sources/Constant', [model '/inferred_Const_F200_Value'], 'MakeNameUnique', 'off');
set_param([model '/inferred_Const_F200_Value'], 'Position', [40 805 190 851]);
set_param([model '/inferred_Const_F200_Value'], 'Value', '208.0');

% Constant: inferred_Const_Constant_Value_c
% Source trace: <S4>/Constant (inferred)
add_block('simulink/Sources/Constant', [model '/inferred_Const_Constant_Value_c'], 'MakeNameUnique', 'off');
set_param([model '/inferred_Const_Constant_Value_c'], 'Position', [40 720 190 766]);
set_param([model '/inferred_Const_Constant_Value_c'], 'Value', '6.84');

% Constant: inferred_Const_Constant1_Value_h
% Source trace: <S4>/Constant1 (inferred)
add_block('simulink/Sources/Constant', [model '/inferred_Const_Constant1_Value_h'], 'MakeNameUnique', 'off');
set_param([model '/inferred_Const_Constant1_Value_h'], 'Position', [40 380 190 426]);
set_param([model '/inferred_Const_Constant1_Value_h'], 'Value', '0.14');

% Constant: inferred_Const_Constant2_Value
% Source trace: <S4>/Constant2 (inferred)
add_block('simulink/Sources/Constant', [model '/inferred_Const_Constant2_Value'], 'MakeNameUnique', 'off');
set_param([model '/inferred_Const_Constant2_Value'], 'Position', [40 550 190 596]);
set_param([model '/inferred_Const_Constant2_Value'], 'Value', '1.0');


% Connect inferred signal dependencies.
fprintf('[connection] Creating %d signal lines with autorouting.\n', expectedLineCount);
try
    add_line(model, 'S2_Saturation/1', 'L2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation', 'L2', ME.message);
end
try
    add_line(model, 'Root_Ti/1', 'Root_FeedbackInt/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_Ti', 'Root_FeedbackInt', ME.message);
end
try
    add_line(model, 'Root_L2_Set_Point/1', 'Root_Sum/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_L2_Set_Point', 'Root_Sum', ME.message);
end
try
    add_line(model, 'S2_Saturation/1', 'Root_Sum/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation', 'Root_Sum', ME.message);
end
try
    add_line(model, 'inferred_Const_F2_Value/1', 'Root_Sum1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_F2_Value', 'Root_Sum1', ME.message);
end
try
    add_line(model, 'Root_Sum2/1', 'Root_Sum1/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_Sum2', 'Root_Sum1', ME.message);
end
try
    add_line(model, 'S1_Slider_Gain/1', 'Root_Sum2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S1_Slider_Gain', 'Root_Sum2', ME.message);
end
try
    add_line(model, 'Root_FeedbackInt/1', 'Root_Sum2/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_FeedbackInt', 'Root_Sum2', ME.message);
end
try
    add_line(model, 'S1_Slider_Gain/1', 'Root_Ti/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S1_Slider_Gain', 'Root_Ti', ME.message);
end
try
    add_line(model, 'Root_Sum/1', 'S1_Slider_Gain/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_Sum', 'S1_Slider_Gain', ME.message);
end
try
    add_line(model, 'S5_L2Int/1', 'S2_Saturation/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S5_L2Int', 'S2_Saturation', ME.message);
end
try
    add_line(model, 'inferred_Const_P100_Value/1', 'S2_Saturation2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_P100_Value', 'S2_Saturation2', ME.message);
end
try
    add_line(model, 'S3_Integrator/1', 'S2_Saturation3/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S3_Integrator', 'S2_Saturation3', ME.message);
end
try
    add_line(model, 'S7_Saturation/1', 'S2_Saturation4/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Saturation', 'S2_Saturation4', ME.message);
end
try
    add_line(model, 'S4_Gain1/1', 'S2_Saturation5/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S4_Gain1', 'S2_Saturation5', ME.message);
end
try
    add_line(model, 'inferred_Const_F200_Value/1', 'S2_Saturation6/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_F200_Value', 'S2_Saturation6', ME.message);
end
try
    add_line(model, 'S3_Sum/1', 'S3_Gain/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S3_Sum', 'S3_Gain', ME.message);
end
try
    add_line(model, 'S3_Gain/1', 'S3_Integrator/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S3_Gain', 'S3_Integrator', ME.message);
end
try
    add_line(model, 'Root_Sum1/1', 'S3_Sum/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_Sum1', 'S3_Sum', ME.message);
end
try
    add_line(model, 'S3_Integrator/1', 'S3_Sum/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S3_Integrator', 'S3_Sum', ME.message);
end
try
    add_line(model, 'S4_Sum/1', 'S4_Gain/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S4_Sum', 'S4_Gain', ME.message);
end
try
    add_line(model, 'S4_Product1/1', 'S4_Gain1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S4_Product1', 'S4_Gain1', ME.message);
end
try
    add_line(model, 'inferred_Const_Constant_Value_c/1', 'S4_Product/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_Constant_Value_c', 'S4_Product', ME.message);
end
try
    add_line(model, 'inferred_Const_Constant1_Value_h/1', 'S4_Product/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_Constant1_Value_h', 'S4_Product', ME.message);
end
try
    add_line(model, 'S2_Saturation6/1', 'S4_Product/3', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation6', 'S4_Product', ME.message);
end
try
    add_line(model, 'S4_Gain/1', 'S4_Product1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S4_Gain', 'S4_Product1', ME.message);
end
try
    add_line(model, 'S4_Sum1/1', 'S4_Product1/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S4_Sum1', 'S4_Product1', ME.message);
end
try
    add_line(model, 'S7_Sum3/1', 'S4_Sum/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum3', 'S4_Sum', ME.message);
end
try
    add_line(model, 'inferred_Const_T200_Value/1', 'S4_Sum/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_T200_Value', 'S4_Sum', ME.message);
end
try
    add_line(model, 'inferred_Const_Constant2_Value/1', 'S4_Sum1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_Constant2_Value', 'S4_Sum1', ME.message);
end
try
    add_line(model, 'S4_Product/1', 'S4_Sum1/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S4_Product', 'S4_Sum1', ME.message);
end
try
    add_line(model, 'S5_Sum/1', 'S5_Gain/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S5_Sum', 'S5_Gain', ME.message);
end
try
    add_line(model, 'S5_Gain/1', 'S5_L2Int/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S5_Gain', 'S5_L2Int', ME.message);
end
try
    add_line(model, 'Root_F1_Step/1', 'S5_Sum/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_F1_Step', 'S5_Sum', ME.message);
end
try
    add_line(model, 'S2_Saturation3/1', 'S5_Sum/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation3', 'S5_Sum', ME.message);
end
try
    add_line(model, 'S2_Saturation4/1', 'S5_Sum/3', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation4', 'S5_Sum', ME.message);
end
try
    add_line(model, 'S2_Saturation2/1', 'S6_Gain/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation2', 'S6_Gain', ME.message);
end
try
    add_line(model, 'S6_Sum1/1', 'S6_Gain1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S6_Sum1', 'S6_Gain1', ME.message);
end
try
    add_line(model, 'S6_Gain1/1', 'S6_Product/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S6_Gain1', 'S6_Product', ME.message);
end
try
    add_line(model, 'S6_Sum2/1', 'S6_Product/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S6_Sum2', 'S6_Product', ME.message);
end
try
    add_line(model, 'inferred_Const_Constant1_Value/1', 'S6_Sum/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_Constant1_Value', 'S6_Sum', ME.message);
end
try
    add_line(model, 'S6_Gain/1', 'S6_Sum/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S6_Gain', 'S6_Sum', ME.message);
end
try
    add_line(model, 'Root_F1_Step/1', 'S6_Sum1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_F1_Step', 'S6_Sum1', ME.message);
end
try
    add_line(model, 'inferred_Const_F3_Value/1', 'S6_Sum1/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_F3_Value', 'S6_Sum1', ME.message);
end
try
    add_line(model, 'S6_Sum/1', 'S6_Sum2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S6_Sum', 'S6_Sum2', ME.message);
end
try
    add_line(model, 'S7_Sum2/1', 'S6_Sum2/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum2', 'S6_Sum2', ME.message);
end
try
    add_line(model, 'S7_Sum/1', 'S7_Gain/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum', 'S7_Gain', ME.message);
end
try
    add_line(model, 'S7_Sum1/1', 'S7_Gain1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum1', 'S7_Gain1', ME.message);
end
try
    add_line(model, 'S7_Saturation1/1', 'S7_Gain2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Saturation1', 'S7_Gain2', ME.message);
end
try
    add_line(model, 'S7_X2Int/1', 'S7_Gain3/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_X2Int', 'S7_Gain3', ME.message);
end
try
    add_line(model, 'S7_Saturation1/1', 'S7_Gain4/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Saturation1', 'S7_Gain4', ME.message);
end
try
    add_line(model, 'S7_Product2/1', 'S7_Gain5/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Product2', 'S7_Gain5', ME.message);
end
try
    add_line(model, 'S7_Sum4/1', 'S7_Gain6/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum4', 'S7_Gain6', ME.message);
end
try
    add_line(model, 'S7_Gain1/1', 'S7_P2Int/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain1', 'S7_P2Int', ME.message);
end
try
    add_line(model, 'Root_F1_Step/1', 'S7_Product/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_F1_Step', 'S7_Product', ME.message);
end
try
    add_line(model, 'Root_X1_Step/1', 'S7_Product/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_X1_Step', 'S7_Product', ME.message);
end
try
    add_line(model, 'S2_Saturation3/1', 'S7_Product1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation3', 'S7_Product1', ME.message);
end
try
    add_line(model, 'S7_X2Int/1', 'S7_Product1/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_X2Int', 'S7_Product1', ME.message);
end
try
    add_line(model, 'S7_Sum5/1', 'S7_Product2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum5', 'S7_Product2', ME.message);
end
try
    add_line(model, 'Root_F1_Step/1', 'S7_Product2/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_F1_Step', 'S7_Product2', ME.message);
end
try
    add_line(model, 'S7_Gain6/1', 'S7_Saturation/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain6', 'S7_Saturation', ME.message);
end
try
    add_line(model, 'S7_P2Int/1', 'S7_Saturation1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_P2Int', 'S7_Saturation1', ME.message);
end
try
    add_line(model, 'S7_Saturation/1', 'S7_Saturation2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Saturation', 'S7_Saturation2', ME.message);
end
try
    add_line(model, 'S7_Product/1', 'S7_Sum/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Product', 'S7_Sum', ME.message);
end
try
    add_line(model, 'S7_Product1/1', 'S7_Sum/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Product1', 'S7_Sum', ME.message);
end
try
    add_line(model, 'S7_Saturation2/1', 'S7_Sum1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Saturation2', 'S7_Sum1', ME.message);
end
try
    add_line(model, 'S2_Saturation5/1', 'S7_Sum1/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation5', 'S7_Sum1', ME.message);
end
try
    add_line(model, 'S7_Gain3/1', 'S7_Sum2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain3', 'S7_Sum2', ME.message);
end
try
    add_line(model, 'inferred_Const_Constant_Value/1', 'S7_Sum2/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_Constant_Value', 'S7_Sum2', ME.message);
end
try
    add_line(model, 'S7_Gain2/1', 'S7_Sum2/3', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain2', 'S7_Sum2', ME.message);
end
try
    add_line(model, 'S7_Gain4/1', 'S7_Sum3/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain4', 'S7_Sum3', ME.message);
end
try
    add_line(model, 'inferred_Const_Constant1_Value_i/1', 'S7_Sum3/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_Constant1_Value_i', 'S7_Sum3', ME.message);
end
try
    add_line(model, 'S6_Product/1', 'S7_Sum4/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S6_Product', 'S7_Sum4', ME.message);
end
try
    add_line(model, 'S7_Gain5/1', 'S7_Sum4/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain5', 'S7_Sum4', ME.message);
end
try
    add_line(model, 'S7_Sum2/1', 'S7_Sum5/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum2', 'S7_Sum5', ME.message);
end
try
    add_line(model, 'inferred_Const_T1_Value/1', 'S7_Sum5/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_T1_Value', 'S7_Sum5', ME.message);
end
try
    add_line(model, 'S7_Gain/1', 'S7_X2Int/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain', 'S7_X2Int', ME.message);
end

% Validate expected top-level block and signal-line counts.
fprintf('[validation] Checking top-level block and signal-line counts.\n');
actualBlockCount = numel(find_system(model, 'SearchDepth', 1, 'Type', 'Block'));
actualLineCount = numel(find_system(model, 'FindAll', 'on', 'SearchDepth', 1, 'Type', 'line'));
if actualBlockCount ~= expectedBlockCount
    warning('Expected %d blocks, but found %d.', expectedBlockCount, actualBlockCount);
end
if actualLineCount ~= expectedLineCount
    warning('Expected %d signal lines, but found %d.', expectedLineCount, actualLineCount);
end

% Add reconstruction notes and unmapped-code annotations.
try
    ann = Simulink.Annotation(model, 'Layout strategy: Left-to-right signal flow. Blocks are arranged by dependency depth so upstream sources stay left and downstream outputs move right.');
    ann.Position = [30 75 520 110];
catch ME
    warning('Could not add annotation: %s', ME.message);
end
try
    ann = Simulink.Annotation(model, 'This model is inferred from generated C code. Simulink Coder output is not lossless; names, hierarchy, masks, sample times, solver settings, and annotations may differ from the original model.');
    ann.Position = [30 120 520 155];
catch ME
    warning('Could not add annotation: %s', ME.message);
end

fprintf('[save] Saving model to %s.slx.\n', model);
save_system(model);
fprintf('[summary] Blocks: %d; signal lines: %d; model: %s; layout: %s.\n', actualBlockCount, actualLineCount, model, layoutStrategy);
