% Auto-generated by the Python Simulink C reconstruction tool.
% The result is an approximate visualization and starting point.
% Generated from Simulink Coder C, which is not a lossless model format.
% Original model inferred from C: process_PIConstrained
% Layout strategy: Simple subsystem preferred.
% Layout note: A compact top-level diagram uses a few coarse subsystems for controller, plant/process, and inferred parameter helpers.
% Inferred facts are represented as blocks, lines, and annotations.

model = 'reconstructed_model_layout6_simple_subsystems';
originalModelName = 'process_PIConstrained';
layoutStrategy = 'Simple subsystem preferred';
layoutDescription = 'A compact top-level diagram uses a few coarse subsystems for controller, plant/process, and inferred parameter helpers.';
expectedBlockCount = 109;
expectedLineCount = 116;
directMappedBlockCount = 55;
inferredBlockCount = 12;
originalRecoveredBlockCount = 67;
subsystemCount = 3;
fprintf('[parsing] Replaying reconstruction facts parsed from Simulink Coder output for %s.\n', originalModelName);
fprintf('[block creation] Creating %d generated blocks from %d recovered logic blocks.\n', expectedBlockCount, originalRecoveredBlockCount);
fprintf('[inferred-block creation] Inferred logic block names include the word inferred.\n');
fprintf('[layout] %s: %s\n', layoutStrategy, layoutDescription);
fprintf('[layout] Preferred subsystem count: %d.\n', subsystemCount);
if bdIsLoaded(model)
    close_system(model, 0);
end
if exist([model '.slx'], 'file')
    delete([model '.slx']);
end
new_system(model);
open_system(model);

% Add top-level interface blocks.
% Outport: L2
% C expression: process_PIConstrained_B.Saturation
add_block('simulink/Sinks/Out1', [model '/L2'], 'MakeNameUnique', 'off');
set_param([model '/L2'], 'Position', [700 110 770 142]);
set_param([model '/L2'], 'Port', '1');

% Add preferred subsystem shells.
% Subsystem: Controller_Delay
add_block('simulink/Ports & Subsystems/Subsystem', [model '/Controller_Delay'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay'], 'Position', [160 100 330 174]);
try, delete_block([model '/Controller_Delay/In1']); catch, end
try, delete_block([model '/Controller_Delay/Out1']); catch, end

% Subsystem: Plant_Process
add_block('simulink/Ports & Subsystems/Subsystem', [model '/Plant_Process'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process'], 'Position', [430 100 600 174]);
try, delete_block([model '/Plant_Process/In1']); catch, end
try, delete_block([model '/Plant_Process/Out1']); catch, end

% Subsystem: Inferred_Parameters
add_block('simulink/Ports & Subsystems/Subsystem', [model '/Inferred_Parameters'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters'], 'Position', [160 250 330 324]);
try, delete_block([model '/Inferred_Parameters/In1']); catch, end
try, delete_block([model '/Inferred_Parameters/Out1']); catch, end

% Populate subsystem contents.
% Subsystem Inport: Controller_Delay/in_Saturation_1
add_block('simulink/Sources/In1', [model '/Controller_Delay/in_Saturation_1'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/in_Saturation_1'], 'Position', [30 60 60 78]);
set_param([model '/Controller_Delay/in_Saturation_1'], 'Port', '1');

% Subsystem Inport: Controller_Delay/in_F2_Value_2
add_block('simulink/Sources/In1', [model '/Controller_Delay/in_F2_Value_2'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/in_F2_Value_2'], 'Position', [30 102 60 120]);
set_param([model '/Controller_Delay/in_F2_Value_2'], 'Port', '2');

% Subsystem Outport: Controller_Delay/out_Integrator_1
add_block('simulink/Sinks/Out1', [model '/Controller_Delay/out_Integrator_1'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/out_Integrator_1'], 'Position', [1507 60 1542 78]);
set_param([model '/Controller_Delay/out_Integrator_1'], 'Port', '1');

% Subsystem Outport: Controller_Delay/out_F1_Step_2
add_block('simulink/Sinks/Out1', [model '/Controller_Delay/out_F1_Step_2'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/out_F1_Step_2'], 'Position', [1507 102 1542 120]);
set_param([model '/Controller_Delay/out_F1_Step_2'], 'Port', '2');

% Subsystem Outport: Controller_Delay/out_F1_Step_3
add_block('simulink/Sinks/Out1', [model '/Controller_Delay/out_F1_Step_3'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/out_F1_Step_3'], 'Position', [1507 144 1542 162]);
set_param([model '/Controller_Delay/out_F1_Step_3'], 'Port', '3');

% Subsystem Outport: Controller_Delay/out_F1_Step_4
add_block('simulink/Sinks/Out1', [model '/Controller_Delay/out_F1_Step_4'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/out_F1_Step_4'], 'Position', [1507 186 1542 204]);
set_param([model '/Controller_Delay/out_F1_Step_4'], 'Port', '4');

% Subsystem Outport: Controller_Delay/out_X1_Step_5
add_block('simulink/Sinks/Out1', [model '/Controller_Delay/out_X1_Step_5'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/out_X1_Step_5'], 'Position', [1507 228 1542 246]);
set_param([model '/Controller_Delay/out_X1_Step_5'], 'Port', '5');

% Subsystem Outport: Controller_Delay/out_F1_Step_6
add_block('simulink/Sinks/Out1', [model '/Controller_Delay/out_F1_Step_6'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/out_F1_Step_6'], 'Position', [1507 270 1542 288]);
set_param([model '/Controller_Delay/out_F1_Step_6'], 'Port', '6');

% Step: Root_F1_Step
% Source trace: <Root>/F1_Step (certain)
% C expression: process_PIConstrained_P.F1_Step_Y0
add_block('simulink/Sources/Step', [model '/Controller_Delay/Root_F1_Step'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/Root_F1_Step'], 'Position', [160 70 250 110]);
set_param([model '/Controller_Delay/Root_F1_Step'], 'Time', '200.0');
set_param([model '/Controller_Delay/Root_F1_Step'], 'Before', '10.0');
set_param([model '/Controller_Delay/Root_F1_Step'], 'After', '10.0');

% Integrator: Root_FeedbackInt
% Source trace: <Root>/FeedbackInt (certain)
% C expression: process_PIConstrained_B.Ti
add_block('simulink/Continuous/Integrator', [model '/Controller_Delay/Root_FeedbackInt'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/Root_FeedbackInt'], 'Position', [660 70 772 122]);
set_param([model '/Controller_Delay/Root_FeedbackInt'], 'InitialCondition', '0.0');

% Step: Root_L2_Set_Point
% Source trace: <Root>/L2 Set Point (certain)
% C expression: process_PIConstrained_P.L2SetPoint_Y0
add_block('simulink/Sources/Step', [model '/Controller_Delay/Root_L2_Set_Point'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/Root_L2_Set_Point'], 'Position', [160 124 280 164]);
set_param([model '/Controller_Delay/Root_L2_Set_Point'], 'Time', '200.0');
set_param([model '/Controller_Delay/Root_L2_Set_Point'], 'Before', '1.0');
set_param([model '/Controller_Delay/Root_L2_Set_Point'], 'After', '1.0');

% Sum: Root_Sum
% Source trace: <Root>/Sum (certain)
% C expression: process_PIConstrained_B.L2SetPoint - process_PIConstrained_B.Saturation
add_block('simulink/Math Operations/Sum', [model '/Controller_Delay/Root_Sum'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/Root_Sum'], 'Position', [285 70 343 112]);
set_param([model '/Controller_Delay/Root_Sum'], 'Inputs', '+-');

% Gain: S1_Slider_Gain
% Source trace: <S1>/Slider Gain (certain)
% C expression: process_PIConstrained_P.L2ProportionalGain_gain * process_PIConstrained_B.Sum_k
add_block('simulink/Math Operations/Gain', [model '/Controller_Delay/S1_Slider_Gain'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/S1_Slider_Gain'], 'Position', [410 70 512 110]);
set_param([model '/Controller_Delay/S1_Slider_Gain'], 'Gain', '-14.18');

% Sum: Root_Sum2
% Source trace: <Root>/Sum2 (certain)
% C expression: process_PIConstrained_B.SliderGain + process_PIConstrained_B.FeedbackInt
add_block('simulink/Math Operations/Sum', [model '/Controller_Delay/Root_Sum2'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/Root_Sum2'], 'Position', [785 70 843 112]);
set_param([model '/Controller_Delay/Root_Sum2'], 'Inputs', '++');

% Sum: Root_Sum1
% Source trace: <Root>/Sum1 (certain)
% C expression: process_PIConstrained_P.F2_Value + process_PIConstrained_B.Sum2_oi
add_block('simulink/Math Operations/Sum', [model '/Controller_Delay/Root_Sum1'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/Root_Sum1'], 'Position', [910 70 968 112]);
set_param([model '/Controller_Delay/Root_Sum1'], 'Inputs', '++');

% Gain: Root_Ti
% Source trace: <Root>/Ti (certain)
% C expression: process_PIConstrained_P.Ti_Gain * process_PIConstrained_B.SliderGain
add_block('simulink/Math Operations/Gain', [model '/Controller_Delay/Root_Ti'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/Root_Ti'], 'Position', [535 70 609 110]);
set_param([model '/Controller_Delay/Root_Ti'], 'Gain', '0.052826201796090863');

% Integrator: S3_Integrator
% Source trace: <S3>/Integrator (certain)
% C expression: process_PIConstrained_B.Gain_b
add_block('simulink/Continuous/Integrator', [model '/Controller_Delay/S3_Integrator'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/S3_Integrator'], 'Position', [1285 70 1397 122]);
set_param([model '/Controller_Delay/S3_Integrator'], 'InitialCondition', '0.0');

% Step: Root_X1_Step
% Source trace: <Root>/X1_Step (certain)
% C expression: process_PIConstrained_P.X1_Step_Y0
add_block('simulink/Sources/Step', [model '/Controller_Delay/Root_X1_Step'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/Root_X1_Step'], 'Position', [160 178 250 218]);
set_param([model '/Controller_Delay/Root_X1_Step'], 'Time', '200.0');
set_param([model '/Controller_Delay/Root_X1_Step'], 'Before', '5.0');
set_param([model '/Controller_Delay/Root_X1_Step'], 'After', '35.0');

% Sum: S3_Sum
% Source trace: <S3>/Sum (certain)
% C expression: process_PIConstrained_B.Sum1_g - process_PIConstrained_B.Integrator
add_block('simulink/Math Operations/Sum', [model '/Controller_Delay/S3_Sum'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/S3_Sum'], 'Position', [1035 70 1093 112]);
set_param([model '/Controller_Delay/S3_Sum'], 'Inputs', '+-');

% Gain: S3_Gain
% Source trace: <S3>/Gain (certain)
% C expression: process_PIConstrained_P.Gain_Gain_hu * process_PIConstrained_B.Sum_iw
add_block('simulink/Math Operations/Gain', [model '/Controller_Delay/S3_Gain'], 'MakeNameUnique', 'off');
set_param([model '/Controller_Delay/S3_Gain'], 'Position', [1160 70 1234 110]);
set_param([model '/Controller_Delay/S3_Gain'], 'Gain', '0.83333333333333337');

% Subsystem Inport: Plant_Process/in_P100_Value_1
add_block('simulink/Sources/In1', [model '/Plant_Process/in_P100_Value_1'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/in_P100_Value_1'], 'Position', [30 60 60 78]);
set_param([model '/Plant_Process/in_P100_Value_1'], 'Port', '1');

% Subsystem Inport: Plant_Process/in_Integrator_2
add_block('simulink/Sources/In1', [model '/Plant_Process/in_Integrator_2'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/in_Integrator_2'], 'Position', [30 102 60 120]);
set_param([model '/Plant_Process/in_Integrator_2'], 'Port', '2');

% Subsystem Inport: Plant_Process/in_F200_Value_3
add_block('simulink/Sources/In1', [model '/Plant_Process/in_F200_Value_3'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/in_F200_Value_3'], 'Position', [30 144 60 162]);
set_param([model '/Plant_Process/in_F200_Value_3'], 'Port', '3');

% Subsystem Inport: Plant_Process/in_Constant_Value_c_4
add_block('simulink/Sources/In1', [model '/Plant_Process/in_Constant_Value_c_4'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/in_Constant_Value_c_4'], 'Position', [30 186 60 204]);
set_param([model '/Plant_Process/in_Constant_Value_c_4'], 'Port', '4');

% Subsystem Inport: Plant_Process/in_Constant1_Value_h_5
add_block('simulink/Sources/In1', [model '/Plant_Process/in_Constant1_Value_h_5'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/in_Constant1_Value_h_5'], 'Position', [30 228 60 246]);
set_param([model '/Plant_Process/in_Constant1_Value_h_5'], 'Port', '5');

% Subsystem Inport: Plant_Process/in_T200_Value_6
add_block('simulink/Sources/In1', [model '/Plant_Process/in_T200_Value_6'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/in_T200_Value_6'], 'Position', [30 270 60 288]);
set_param([model '/Plant_Process/in_T200_Value_6'], 'Port', '6');

% Subsystem Inport: Plant_Process/in_Constant2_Value_7
add_block('simulink/Sources/In1', [model '/Plant_Process/in_Constant2_Value_7'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/in_Constant2_Value_7'], 'Position', [30 312 60 330]);
set_param([model '/Plant_Process/in_Constant2_Value_7'], 'Port', '7');

% Subsystem Inport: Plant_Process/in_F1_Step_8
add_block('simulink/Sources/In1', [model '/Plant_Process/in_F1_Step_8'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/in_F1_Step_8'], 'Position', [30 354 60 372]);
set_param([model '/Plant_Process/in_F1_Step_8'], 'Port', '8');

% Subsystem Inport: Plant_Process/in_Constant1_Value_9
add_block('simulink/Sources/In1', [model '/Plant_Process/in_Constant1_Value_9'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/in_Constant1_Value_9'], 'Position', [30 396 60 414]);
set_param([model '/Plant_Process/in_Constant1_Value_9'], 'Port', '9');

% Subsystem Inport: Plant_Process/in_F1_Step_10
add_block('simulink/Sources/In1', [model '/Plant_Process/in_F1_Step_10'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/in_F1_Step_10'], 'Position', [30 438 60 456]);
set_param([model '/Plant_Process/in_F1_Step_10'], 'Port', '10');

% Subsystem Inport: Plant_Process/in_F3_Value_11
add_block('simulink/Sources/In1', [model '/Plant_Process/in_F3_Value_11'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/in_F3_Value_11'], 'Position', [30 480 60 498]);
set_param([model '/Plant_Process/in_F3_Value_11'], 'Port', '11');

% Subsystem Inport: Plant_Process/in_F1_Step_12
add_block('simulink/Sources/In1', [model '/Plant_Process/in_F1_Step_12'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/in_F1_Step_12'], 'Position', [30 522 60 540]);
set_param([model '/Plant_Process/in_F1_Step_12'], 'Port', '12');

% Subsystem Inport: Plant_Process/in_X1_Step_13
add_block('simulink/Sources/In1', [model '/Plant_Process/in_X1_Step_13'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/in_X1_Step_13'], 'Position', [30 564 60 582]);
set_param([model '/Plant_Process/in_X1_Step_13'], 'Port', '13');

% Subsystem Inport: Plant_Process/in_F1_Step_14
add_block('simulink/Sources/In1', [model '/Plant_Process/in_F1_Step_14'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/in_F1_Step_14'], 'Position', [30 606 60 624]);
set_param([model '/Plant_Process/in_F1_Step_14'], 'Port', '14');

% Subsystem Inport: Plant_Process/in_Constant_Value_15
add_block('simulink/Sources/In1', [model '/Plant_Process/in_Constant_Value_15'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/in_Constant_Value_15'], 'Position', [30 648 60 666]);
set_param([model '/Plant_Process/in_Constant_Value_15'], 'Port', '15');

% Subsystem Inport: Plant_Process/in_Constant1_Value_i_16
add_block('simulink/Sources/In1', [model '/Plant_Process/in_Constant1_Value_i_16'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/in_Constant1_Value_i_16'], 'Position', [30 690 60 708]);
set_param([model '/Plant_Process/in_Constant1_Value_i_16'], 'Port', '16');

% Subsystem Inport: Plant_Process/in_T1_Value_17
add_block('simulink/Sources/In1', [model '/Plant_Process/in_T1_Value_17'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/in_T1_Value_17'], 'Position', [30 732 60 750]);
set_param([model '/Plant_Process/in_T1_Value_17'], 'Port', '17');

% Subsystem Outport: Plant_Process/out_Saturation_1
add_block('simulink/Sinks/Out1', [model '/Plant_Process/out_Saturation_1'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/out_Saturation_1'], 'Position', [1469 60 1504 78]);
set_param([model '/Plant_Process/out_Saturation_1'], 'Port', '1');

% Subsystem Outport: Plant_Process/out_Saturation_2
add_block('simulink/Sinks/Out1', [model '/Plant_Process/out_Saturation_2'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/out_Saturation_2'], 'Position', [1469 102 1504 120]);
set_param([model '/Plant_Process/out_Saturation_2'], 'Port', '2');

% Integrator: S5_L2Int
% Source trace: <S5>/L2Int (certain)
% C expression: process_PIConstrained_B.Gain_g
add_block('simulink/Continuous/Integrator', [model '/Plant_Process/S5_L2Int'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S5_L2Int'], 'Position', [660 556 772 608]);
set_param([model '/Plant_Process/S5_L2Int'], 'InitialCondition', '1.0');

% Saturation: S2_Saturation
% Source trace: <S2>/Saturation (certain)
% C expression: (process_PIConstrained_P.Saturation_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/Plant_Process/S2_Saturation'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S2_Saturation'], 'Position', [785 556 881 598]);
set_param([model '/Plant_Process/S2_Saturation'], 'LowerLimit', '0.0');
set_param([model '/Plant_Process/S2_Saturation'], 'UpperLimit', '2.0');

% Sum: S6_Sum1
% Source trace: <S6>/Sum1 (certain)
% C expression: process_PIConstrained_B.F1_Step + process_PIConstrained_P.F3_Value
add_block('simulink/Math Operations/Sum', [model '/Plant_Process/S6_Sum1'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S6_Sum1'], 'Position', [160 232 218 274]);
set_param([model '/Plant_Process/S6_Sum1'], 'Inputs', '++');

% Gain: S6_Gain1
% Source trace: <S6>/Gain1 (certain)
% C expression: process_PIConstrained_P.Gain1_Gain * process_PIConstrained_B.Sum1
add_block('simulink/Math Operations/Gain', [model '/Plant_Process/S6_Gain1'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S6_Gain1'], 'Position', [285 178 359 218]);
set_param([model '/Plant_Process/S6_Gain1'], 'Gain', '0.16');

% Saturation: S2_Saturation2
% Source trace: <S2>/Saturation2 (certain)
% C expression: (process_PIConstrained_P.Saturation2_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/Plant_Process/S2_Saturation2'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S2_Saturation2'], 'Position', [160 70 256 112]);
set_param([model '/Plant_Process/S2_Saturation2'], 'LowerLimit', '0.0');
set_param([model '/Plant_Process/S2_Saturation2'], 'UpperLimit', '400.0');

% Gain: S6_Gain
% Source trace: <S6>/Gain (certain)
% C expression: process_PIConstrained_P.Gain_Gain * process_PIConstrained_B.Saturation2
add_block('simulink/Math Operations/Gain', [model '/Plant_Process/S6_Gain'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S6_Gain'], 'Position', [285 124 359 164]);
set_param([model '/Plant_Process/S6_Gain'], 'Gain', '0.1538');

% Sum: S6_Sum
% Source trace: <S6>/Sum (certain)
% C expression: process_PIConstrained_P.Constant1_Value + process_PIConstrained_B.Gain
add_block('simulink/Math Operations/Sum', [model '/Plant_Process/S6_Sum'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S6_Sum'], 'Position', [410 124 468 166]);
set_param([model '/Plant_Process/S6_Sum'], 'Inputs', '++');

% Integrator: S7_X2Int
% Source trace: <S7>/X2Int (certain)
% C expression: process_PIConstrained_B.Gain_a
add_block('simulink/Continuous/Integrator', [model '/Plant_Process/S7_X2Int'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_X2Int'], 'Position', [785 124 897 176]);
set_param([model '/Plant_Process/S7_X2Int'], 'InitialCondition', '25.0');

% Gain: S7_Gain3
% Source trace: <S7>/Gain3 (certain)
% C expression: process_PIConstrained_P.Gain3_Gain * process_PIConstrained_B.X2Int
add_block('simulink/Math Operations/Gain', [model '/Plant_Process/S7_Gain3'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Gain3'], 'Position', [910 124 984 164]);
set_param([model '/Plant_Process/S7_Gain3'], 'Gain', '0.3126');

% Integrator: S7_P2Int
% Source trace: <S7>/P2Int (certain)
% C expression: process_PIConstrained_B.Gain1_f
add_block('simulink/Continuous/Integrator', [model '/Plant_Process/S7_P2Int'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_P2Int'], 'Position', [285 394 397 446]);
set_param([model '/Plant_Process/S7_P2Int'], 'InitialCondition', '50.5');

% Saturation: S7_Saturation1
% Source trace: <S7>/Saturation1 (certain)
% C expression: (process_PIConstrained_P.Saturation1_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/Plant_Process/S7_Saturation1'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Saturation1'], 'Position', [410 394 506 436]);
set_param([model '/Plant_Process/S7_Saturation1'], 'LowerLimit', '0.0');
set_param([model '/Plant_Process/S7_Saturation1'], 'UpperLimit', '100.0');

% Gain: S7_Gain2
% Source trace: <S7>/Gain2 (certain)
% C expression: process_PIConstrained_P.Gain2_Gain * process_PIConstrained_B.Saturation1
add_block('simulink/Math Operations/Gain', [model '/Plant_Process/S7_Gain2'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Gain2'], 'Position', [535 394 609 434]);
set_param([model '/Plant_Process/S7_Gain2'], 'Gain', '0.5616');

% Sum: S7_Sum2
% Source trace: <S7>/Sum2 (certain)
% C expression: (process_PIConstrained_B.Gain3 + process_PIConstrained_P.Constant_Value) + process_PIConstrained_B.Gain2
add_block('simulink/Math Operations/Sum', [model '/Plant_Process/S7_Sum2'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Sum2'], 'Position', [660 394 718 436]);
set_param([model '/Plant_Process/S7_Sum2'], 'Inputs', '+++');

% Sum: S6_Sum2
% Source trace: <S6>/Sum2 (certain)
% C expression: process_PIConstrained_B.Sum - process_PIConstrained_B.Sum2
add_block('simulink/Math Operations/Sum', [model '/Plant_Process/S6_Sum2'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S6_Sum2'], 'Position', [785 394 843 436]);
set_param([model '/Plant_Process/S6_Sum2'], 'Inputs', '+-');

% Product: S6_Product
% Source trace: <S6>/Product (certain)
% C expression: process_PIConstrained_B.Gain1 * process_PIConstrained_B.Sum2_o
add_block('simulink/Math Operations/Product', [model '/Plant_Process/S6_Product'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S6_Product'], 'Position', [910 394 968 436]);
set_param([model '/Plant_Process/S6_Product'], 'Inputs', '**');

% Sum: S7_Sum5
% Source trace: <S7>/Sum5 (certain)
% C expression: process_PIConstrained_B.Sum2 - process_PIConstrained_P.T1_Value
add_block('simulink/Math Operations/Sum', [model '/Plant_Process/S7_Sum5'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Sum5'], 'Position', [785 448 843 490]);
set_param([model '/Plant_Process/S7_Sum5'], 'Inputs', '+-');

% Product: S7_Product2
% Source trace: <S7>/Product2 (certain)
% C expression: process_PIConstrained_B.Sum5 * process_PIConstrained_B.F1_Step
add_block('simulink/Math Operations/Product', [model '/Plant_Process/S7_Product2'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Product2'], 'Position', [910 448 968 490]);
set_param([model '/Plant_Process/S7_Product2'], 'Inputs', '**');

% Gain: S7_Gain5
% Source trace: <S7>/Gain5 (certain)
% C expression: process_PIConstrained_P.Gain5_Gain * process_PIConstrained_B.Product2
add_block('simulink/Math Operations/Gain', [model '/Plant_Process/S7_Gain5'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Gain5'], 'Position', [1035 394 1109 434]);
set_param([model '/Plant_Process/S7_Gain5'], 'Gain', '0.07');

% Sum: S7_Sum4
% Source trace: <S7>/Sum4 (certain)
% C expression: process_PIConstrained_B.Product - process_PIConstrained_B.Gain5
add_block('simulink/Math Operations/Sum', [model '/Plant_Process/S7_Sum4'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Sum4'], 'Position', [1160 394 1218 436]);
set_param([model '/Plant_Process/S7_Sum4'], 'Inputs', '+-');

% Gain: S7_Gain6
% Source trace: <S7>/Gain6 (certain)
% C expression: process_PIConstrained_P.Gain6_Gain * process_PIConstrained_B.Sum4
add_block('simulink/Math Operations/Gain', [model '/Plant_Process/S7_Gain6'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Gain6'], 'Position', [1285 394 1359 434]);
set_param([model '/Plant_Process/S7_Gain6'], 'Gain', '0.025974025974025976');

% Saturation: S7_Saturation
% Source trace: <S7>/Saturation (certain)
% C expression: (process_PIConstrained_P.Saturation_UpperSat_p)
add_block('simulink/Discontinuities/Saturation', [model '/Plant_Process/S7_Saturation'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Saturation'], 'Position', [160 556 256 598]);
set_param([model '/Plant_Process/S7_Saturation'], 'LowerLimit', '0.0');
set_param([model '/Plant_Process/S7_Saturation'], 'UpperLimit', '16.0');

% Saturation: S2_Saturation4
% Source trace: <S2>/Saturation4 (certain)
% C expression: (process_PIConstrained_P.Saturation4_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/Plant_Process/S2_Saturation4'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S2_Saturation4'], 'Position', [285 556 381 598]);
set_param([model '/Plant_Process/S2_Saturation4'], 'LowerLimit', '0.0');
set_param([model '/Plant_Process/S2_Saturation4'], 'UpperLimit', '16.0');

% Gain: S7_Gain4
% Source trace: <S7>/Gain4 (certain)
% C expression: process_PIConstrained_P.Gain4_Gain * process_PIConstrained_B.Saturation1
add_block('simulink/Math Operations/Gain', [model '/Plant_Process/S7_Gain4'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Gain4'], 'Position', [410 178 484 218]);
set_param([model '/Plant_Process/S7_Gain4'], 'Gain', '0.507');

% Sum: S7_Sum3
% Source trace: <S7>/Sum3 (certain)
% C expression: process_PIConstrained_B.Gain4 + process_PIConstrained_P.Constant1_Value_i
add_block('simulink/Math Operations/Sum', [model '/Plant_Process/S7_Sum3'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Sum3'], 'Position', [535 124 593 166]);
set_param([model '/Plant_Process/S7_Sum3'], 'Inputs', '++');

% Sum: S4_Sum
% Source trace: <S4>/Sum (certain)
% C expression: process_PIConstrained_B.Sum3 - process_PIConstrained_P.T200_Value
add_block('simulink/Math Operations/Sum', [model '/Plant_Process/S4_Sum'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S4_Sum'], 'Position', [660 70 718 112]);
set_param([model '/Plant_Process/S4_Sum'], 'Inputs', '+-');

% Gain: S4_Gain
% Source trace: <S4>/Gain (certain)
% C expression: process_PIConstrained_P.Gain_Gain_h * process_PIConstrained_B.Sum_d
add_block('simulink/Math Operations/Gain', [model '/Plant_Process/S4_Gain'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S4_Gain'], 'Position', [785 70 859 110]);
set_param([model '/Plant_Process/S4_Gain'], 'Gain', '6.84');

% Saturation: S2_Saturation6
% Source trace: <S2>/Saturation6 (certain)
% C expression: (process_PIConstrained_P.Saturation6_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/Plant_Process/S2_Saturation6'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S2_Saturation6'], 'Position', [160 178 256 220]);
set_param([model '/Plant_Process/S2_Saturation6'], 'LowerLimit', '0.0');
set_param([model '/Plant_Process/S2_Saturation6'], 'UpperLimit', '416.0');

% Product: S4_Product
% Source trace: <S4>/Product (certain)
% C expression: process_PIConstrained_P.Constant_Value_c / process_PIConstrained_P.Constant1_Value_h / process_PIConstrained_B.Saturation6
add_block('simulink/Math Operations/Product', [model '/Plant_Process/S4_Product'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S4_Product'], 'Position', [285 70 343 112]);
set_param([model '/Plant_Process/S4_Product'], 'Inputs', '*//');

% Sum: S4_Sum1
% Source trace: <S4>/Sum1 (certain)
% C expression: process_PIConstrained_P.Constant2_Value + process_PIConstrained_B.Product_k
add_block('simulink/Math Operations/Sum', [model '/Plant_Process/S4_Sum1'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S4_Sum1'], 'Position', [410 70 468 112]);
set_param([model '/Plant_Process/S4_Sum1'], 'Inputs', '++');

% Product: S4_Product1
% Source trace: <S4>/Product1 (certain)
% C expression: process_PIConstrained_B.Gain_c / process_PIConstrained_B.Sum1_h
add_block('simulink/Math Operations/Product', [model '/Plant_Process/S4_Product1'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S4_Product1'], 'Position', [910 70 968 112]);
set_param([model '/Plant_Process/S4_Product1'], 'Inputs', '*/');

% Gain: S4_Gain1
% Source trace: <S4>/Gain1 (certain)
% C expression: process_PIConstrained_P.Gain1_Gain_l * process_PIConstrained_B.Q200
add_block('simulink/Math Operations/Gain', [model '/Plant_Process/S4_Gain1'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S4_Gain1'], 'Position', [1035 70 1109 110]);
set_param([model '/Plant_Process/S4_Gain1'], 'Gain', '0.025974025974025976');

% Saturation: S2_Saturation3
% Source trace: <S2>/Saturation3 (certain)
% C expression: (process_PIConstrained_P.Saturation3_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/Plant_Process/S2_Saturation3'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S2_Saturation3'], 'Position', [160 124 256 166]);
set_param([model '/Plant_Process/S2_Saturation3'], 'LowerLimit', '0.0');
set_param([model '/Plant_Process/S2_Saturation3'], 'UpperLimit', '4.0');

% Saturation: S2_Saturation5
% Source trace: <S2>/Saturation5 (certain)
% C expression: (process_PIConstrained_P.Saturation5_UpperSat)
add_block('simulink/Discontinuities/Saturation', [model '/Plant_Process/S2_Saturation5'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S2_Saturation5'], 'Position', [1160 70 1256 112]);
set_param([model '/Plant_Process/S2_Saturation5'], 'LowerLimit', '0.0');
set_param([model '/Plant_Process/S2_Saturation5'], 'UpperLimit', '16.0');

% Sum: S5_Sum
% Source trace: <S5>/Sum (certain)
% C expression: (process_PIConstrained_B.F1_Step - process_PIConstrained_B.Saturation3) - process_PIConstrained_B.Saturation4
add_block('simulink/Math Operations/Sum', [model '/Plant_Process/S5_Sum'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S5_Sum'], 'Position', [410 556 468 598]);
set_param([model '/Plant_Process/S5_Sum'], 'Inputs', '+--');

% Gain: S5_Gain
% Source trace: <S5>/Gain (certain)
% C expression: process_PIConstrained_P.Gain_Gain_k * process_PIConstrained_B.Sum_m
add_block('simulink/Math Operations/Gain', [model '/Plant_Process/S5_Gain'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S5_Gain'], 'Position', [535 556 609 596]);
set_param([model '/Plant_Process/S5_Gain'], 'Gain', '0.05');

% Product: S7_Product
% Source trace: <S7>/Product (certain)
% C expression: process_PIConstrained_B.F1_Step * process_PIConstrained_B.X1_Step
add_block('simulink/Math Operations/Product', [model '/Plant_Process/S7_Product'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Product'], 'Position', [160 286 218 328]);
set_param([model '/Plant_Process/S7_Product'], 'Inputs', '**');

% Product: S7_Product1
% Source trace: <S7>/Product1 (certain)
% C expression: process_PIConstrained_B.Saturation3 * process_PIConstrained_B.X2Int
add_block('simulink/Math Operations/Product', [model '/Plant_Process/S7_Product1'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Product1'], 'Position', [410 232 468 274]);
set_param([model '/Plant_Process/S7_Product1'], 'Inputs', '**');

% Sum: S7_Sum
% Source trace: <S7>/Sum (certain)
% C expression: process_PIConstrained_B.Product_c - process_PIConstrained_B.Product1
add_block('simulink/Math Operations/Sum', [model '/Plant_Process/S7_Sum'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Sum'], 'Position', [535 70 593 112]);
set_param([model '/Plant_Process/S7_Sum'], 'Inputs', '+-');

% Gain: S7_Gain
% Source trace: <S7>/Gain (certain)
% C expression: process_PIConstrained_P.Gain_Gain_n * process_PIConstrained_B.Sum_i
add_block('simulink/Math Operations/Gain', [model '/Plant_Process/S7_Gain'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Gain'], 'Position', [660 124 734 164]);
set_param([model '/Plant_Process/S7_Gain'], 'Gain', '0.05');

% Saturation: S7_Saturation2
% Source trace: <S7>/Saturation2 (certain)
% C expression: (process_PIConstrained_P.Saturation2_UpperSat_l)
add_block('simulink/Discontinuities/Saturation', [model '/Plant_Process/S7_Saturation2'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Saturation2'], 'Position', [410 286 506 328]);
set_param([model '/Plant_Process/S7_Saturation2'], 'LowerLimit', '0.0');
set_param([model '/Plant_Process/S7_Saturation2'], 'UpperLimit', '16.0');

% Sum: S7_Sum1
% Source trace: <S7>/Sum1 (certain)
% C expression: process_PIConstrained_B.Saturation2_e - process_PIConstrained_B.Saturation5
add_block('simulink/Math Operations/Sum', [model '/Plant_Process/S7_Sum1'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Sum1'], 'Position', [1285 70 1343 112]);
set_param([model '/Plant_Process/S7_Sum1'], 'Inputs', '+-');

% Gain: S7_Gain1
% Source trace: <S7>/Gain1 (certain)
% C expression: process_PIConstrained_P.Gain1_Gain_m * process_PIConstrained_B.Sum1_e
add_block('simulink/Math Operations/Gain', [model '/Plant_Process/S7_Gain1'], 'MakeNameUnique', 'off');
set_param([model '/Plant_Process/S7_Gain1'], 'Position', [160 394 234 434]);
set_param([model '/Plant_Process/S7_Gain1'], 'Gain', '0.25');

% Subsystem Outport: Inferred_Parameters/out_F2_Value_1
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_F2_Value_1'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_F2_Value_1'], 'Position', [402 60 437 78]);
set_param([model '/Inferred_Parameters/out_F2_Value_1'], 'Port', '1');

% Subsystem Outport: Inferred_Parameters/out_P100_Value_2
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_P100_Value_2'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_P100_Value_2'], 'Position', [402 102 437 120]);
set_param([model '/Inferred_Parameters/out_P100_Value_2'], 'Port', '2');

% Subsystem Outport: Inferred_Parameters/out_F200_Value_3
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_F200_Value_3'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_F200_Value_3'], 'Position', [402 144 437 162]);
set_param([model '/Inferred_Parameters/out_F200_Value_3'], 'Port', '3');

% Subsystem Outport: Inferred_Parameters/out_Constant_Value_c_4
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_Constant_Value_c_4'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_Constant_Value_c_4'], 'Position', [402 186 437 204]);
set_param([model '/Inferred_Parameters/out_Constant_Value_c_4'], 'Port', '4');

% Subsystem Outport: Inferred_Parameters/out_Constant1_Value_h_5
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_Constant1_Value_h_5'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_Constant1_Value_h_5'], 'Position', [402 228 437 246]);
set_param([model '/Inferred_Parameters/out_Constant1_Value_h_5'], 'Port', '5');

% Subsystem Outport: Inferred_Parameters/out_T200_Value_6
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_T200_Value_6'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_T200_Value_6'], 'Position', [402 270 437 288]);
set_param([model '/Inferred_Parameters/out_T200_Value_6'], 'Port', '6');

% Subsystem Outport: Inferred_Parameters/out_Constant2_Value_7
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_Constant2_Value_7'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_Constant2_Value_7'], 'Position', [402 312 437 330]);
set_param([model '/Inferred_Parameters/out_Constant2_Value_7'], 'Port', '7');

% Subsystem Outport: Inferred_Parameters/out_Constant1_Value_8
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_Constant1_Value_8'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_Constant1_Value_8'], 'Position', [402 354 437 372]);
set_param([model '/Inferred_Parameters/out_Constant1_Value_8'], 'Port', '8');

% Subsystem Outport: Inferred_Parameters/out_F3_Value_9
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_F3_Value_9'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_F3_Value_9'], 'Position', [402 396 437 414]);
set_param([model '/Inferred_Parameters/out_F3_Value_9'], 'Port', '9');

% Subsystem Outport: Inferred_Parameters/out_Constant_Value_10
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_Constant_Value_10'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_Constant_Value_10'], 'Position', [402 438 437 456]);
set_param([model '/Inferred_Parameters/out_Constant_Value_10'], 'Port', '10');

% Subsystem Outport: Inferred_Parameters/out_Constant1_Value_i_11
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_Constant1_Value_i_11'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_Constant1_Value_i_11'], 'Position', [402 480 437 498]);
set_param([model '/Inferred_Parameters/out_Constant1_Value_i_11'], 'Port', '11');

% Subsystem Outport: Inferred_Parameters/out_T1_Value_12
add_block('simulink/Sinks/Out1', [model '/Inferred_Parameters/out_T1_Value_12'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/out_T1_Value_12'], 'Position', [402 522 437 540]);
set_param([model '/Inferred_Parameters/out_T1_Value_12'], 'Port', '12');

% Constant: inferred_Const_F3_Value
% Source trace: <Root>/F3 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_F3_Value'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_F3_Value'], 'Position', [160 502 292 542]);
set_param([model '/Inferred_Parameters/inferred_Const_F3_Value'], 'Value', '50.0');

% Constant: inferred_Const_P100_Value
% Source trace: <Root>/P100 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_P100_Value'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_P100_Value'], 'Position', [160 556 292 596]);
set_param([model '/Inferred_Parameters/inferred_Const_P100_Value'], 'Value', '194.7');

% Constant: inferred_Const_Constant1_Value
% Source trace: <S6>/Constant1 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_Constant1_Value'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_Constant1_Value'], 'Position', [160 70 292 110]);
set_param([model '/Inferred_Parameters/inferred_Const_Constant1_Value'], 'Value', '90.0');

% Constant: inferred_Const_Constant_Value
% Source trace: <S7>/Constant (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_Constant_Value'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_Constant_Value'], 'Position', [160 286 292 326]);
set_param([model '/Inferred_Parameters/inferred_Const_Constant_Value'], 'Value', '48.43');

% Constant: inferred_Const_T1_Value
% Source trace: <Root>/T1 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_T1_Value'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_T1_Value'], 'Position', [160 610 292 650]);
set_param([model '/Inferred_Parameters/inferred_Const_T1_Value'], 'Value', '40.0');

% Constant: inferred_Const_F2_Value
% Source trace: <Root>/F2 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_F2_Value'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_F2_Value'], 'Position', [160 448 292 488]);
set_param([model '/Inferred_Parameters/inferred_Const_F2_Value'], 'Value', '2.0');

% Constant: inferred_Const_Constant1_Value_i
% Source trace: <S7>/Constant1 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_Constant1_Value_i'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_Constant1_Value_i'], 'Position', [160 178 292 218]);
set_param([model '/Inferred_Parameters/inferred_Const_Constant1_Value_i'], 'Value', '55.0');

% Constant: inferred_Const_T200_Value
% Source trace: <Root>/T200 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_T200_Value'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_T200_Value'], 'Position', [160 664 292 704]);
set_param([model '/Inferred_Parameters/inferred_Const_T200_Value'], 'Value', '25.0');

% Constant: inferred_Const_F200_Value
% Source trace: <Root>/F200 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_F200_Value'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_F200_Value'], 'Position', [160 394 292 434]);
set_param([model '/Inferred_Parameters/inferred_Const_F200_Value'], 'Value', '208.0');

% Constant: inferred_Const_Constant_Value_c
% Source trace: <S4>/Constant (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_Constant_Value_c'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_Constant_Value_c'], 'Position', [160 340 292 380]);
set_param([model '/Inferred_Parameters/inferred_Const_Constant_Value_c'], 'Value', '6.84');

% Constant: inferred_Const_Constant1_Value_h
% Source trace: <S4>/Constant1 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_Constant1_Value_h'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_Constant1_Value_h'], 'Position', [160 124 292 164]);
set_param([model '/Inferred_Parameters/inferred_Const_Constant1_Value_h'], 'Value', '0.14');

% Constant: inferred_Const_Constant2_Value
% Source trace: <S4>/Constant2 (inferred)
add_block('simulink/Sources/Constant', [model '/Inferred_Parameters/inferred_Const_Constant2_Value'], 'MakeNameUnique', 'off');
set_param([model '/Inferred_Parameters/inferred_Const_Constant2_Value'], 'Position', [160 232 292 272]);
set_param([model '/Inferred_Parameters/inferred_Const_Constant2_Value'], 'Value', '1.0');

% Connect internal subsystem signal dependencies.
fprintf('[connection] Creating %d generated signal lines, including subsystem bridge lines.\n', expectedLineCount);
try
    add_line([model '/Controller_Delay'], 'Root_Ti/1', 'Root_FeedbackInt/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_Ti', 'Root_FeedbackInt', ME.message);
end
try
    add_line([model '/Controller_Delay'], 'Root_L2_Set_Point/1', 'Root_Sum/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_L2_Set_Point', 'Root_Sum', ME.message);
end
try
    add_line([model '/Controller_Delay'], 'in_Saturation_1/1', 'Root_Sum/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Saturation_1', 'Root_Sum', ME.message);
end
try
    add_line([model '/Controller_Delay'], 'in_F2_Value_2/1', 'Root_Sum1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_F2_Value_2', 'Root_Sum1', ME.message);
end
try
    add_line([model '/Controller_Delay'], 'Root_Sum2/1', 'Root_Sum1/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_Sum2', 'Root_Sum1', ME.message);
end
try
    add_line([model '/Controller_Delay'], 'S1_Slider_Gain/1', 'Root_Sum2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S1_Slider_Gain', 'Root_Sum2', ME.message);
end
try
    add_line([model '/Controller_Delay'], 'Root_FeedbackInt/1', 'Root_Sum2/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_FeedbackInt', 'Root_Sum2', ME.message);
end
try
    add_line([model '/Controller_Delay'], 'S1_Slider_Gain/1', 'Root_Ti/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S1_Slider_Gain', 'Root_Ti', ME.message);
end
try
    add_line([model '/Controller_Delay'], 'Root_Sum/1', 'S1_Slider_Gain/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_Sum', 'S1_Slider_Gain', ME.message);
end
try
    add_line([model '/Controller_Delay'], 'S3_Integrator/1', 'out_Integrator_1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S3_Integrator', 'out_Integrator_1', ME.message);
end
try
    add_line([model '/Controller_Delay'], 'S3_Sum/1', 'S3_Gain/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S3_Sum', 'S3_Gain', ME.message);
end
try
    add_line([model '/Controller_Delay'], 'S3_Gain/1', 'S3_Integrator/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S3_Gain', 'S3_Integrator', ME.message);
end
try
    add_line([model '/Controller_Delay'], 'Root_Sum1/1', 'S3_Sum/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_Sum1', 'S3_Sum', ME.message);
end
try
    add_line([model '/Controller_Delay'], 'S3_Integrator/1', 'S3_Sum/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S3_Integrator', 'S3_Sum', ME.message);
end
try
    add_line([model '/Controller_Delay'], 'Root_F1_Step/1', 'out_F1_Step_2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_F1_Step', 'out_F1_Step_2', ME.message);
end
try
    add_line([model '/Controller_Delay'], 'Root_F1_Step/1', 'out_F1_Step_3/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_F1_Step', 'out_F1_Step_3', ME.message);
end
try
    add_line([model '/Controller_Delay'], 'Root_F1_Step/1', 'out_F1_Step_4/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_F1_Step', 'out_F1_Step_4', ME.message);
end
try
    add_line([model '/Controller_Delay'], 'Root_X1_Step/1', 'out_X1_Step_5/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_X1_Step', 'out_X1_Step_5', ME.message);
end
try
    add_line([model '/Controller_Delay'], 'Root_F1_Step/1', 'out_F1_Step_6/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Root_F1_Step', 'out_F1_Step_6', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S2_Saturation/1', 'out_Saturation_1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation', 'out_Saturation_1', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S2_Saturation/1', 'out_Saturation_2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation', 'out_Saturation_2', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S5_L2Int/1', 'S2_Saturation/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S5_L2Int', 'S2_Saturation', ME.message);
end
try
    add_line([model '/Plant_Process'], 'in_P100_Value_1/1', 'S2_Saturation2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_P100_Value_1', 'S2_Saturation2', ME.message);
end
try
    add_line([model '/Plant_Process'], 'in_Integrator_2/1', 'S2_Saturation3/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Integrator_2', 'S2_Saturation3', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Saturation/1', 'S2_Saturation4/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Saturation', 'S2_Saturation4', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S4_Gain1/1', 'S2_Saturation5/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S4_Gain1', 'S2_Saturation5', ME.message);
end
try
    add_line([model '/Plant_Process'], 'in_F200_Value_3/1', 'S2_Saturation6/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_F200_Value_3', 'S2_Saturation6', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S4_Sum/1', 'S4_Gain/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S4_Sum', 'S4_Gain', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S4_Product1/1', 'S4_Gain1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S4_Product1', 'S4_Gain1', ME.message);
end
try
    add_line([model '/Plant_Process'], 'in_Constant_Value_c_4/1', 'S4_Product/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Constant_Value_c_4', 'S4_Product', ME.message);
end
try
    add_line([model '/Plant_Process'], 'in_Constant1_Value_h_5/1', 'S4_Product/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Constant1_Value_h_5', 'S4_Product', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S2_Saturation6/1', 'S4_Product/3', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation6', 'S4_Product', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S4_Gain/1', 'S4_Product1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S4_Gain', 'S4_Product1', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S4_Sum1/1', 'S4_Product1/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S4_Sum1', 'S4_Product1', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Sum3/1', 'S4_Sum/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum3', 'S4_Sum', ME.message);
end
try
    add_line([model '/Plant_Process'], 'in_T200_Value_6/1', 'S4_Sum/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_T200_Value_6', 'S4_Sum', ME.message);
end
try
    add_line([model '/Plant_Process'], 'in_Constant2_Value_7/1', 'S4_Sum1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Constant2_Value_7', 'S4_Sum1', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S4_Product/1', 'S4_Sum1/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S4_Product', 'S4_Sum1', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S5_Sum/1', 'S5_Gain/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S5_Sum', 'S5_Gain', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S5_Gain/1', 'S5_L2Int/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S5_Gain', 'S5_L2Int', ME.message);
end
try
    add_line([model '/Plant_Process'], 'in_F1_Step_8/1', 'S5_Sum/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_F1_Step_8', 'S5_Sum', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S2_Saturation3/1', 'S5_Sum/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation3', 'S5_Sum', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S2_Saturation4/1', 'S5_Sum/3', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation4', 'S5_Sum', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S2_Saturation2/1', 'S6_Gain/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation2', 'S6_Gain', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S6_Sum1/1', 'S6_Gain1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S6_Sum1', 'S6_Gain1', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S6_Gain1/1', 'S6_Product/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S6_Gain1', 'S6_Product', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S6_Sum2/1', 'S6_Product/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S6_Sum2', 'S6_Product', ME.message);
end
try
    add_line([model '/Plant_Process'], 'in_Constant1_Value_9/1', 'S6_Sum/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Constant1_Value_9', 'S6_Sum', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S6_Gain/1', 'S6_Sum/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S6_Gain', 'S6_Sum', ME.message);
end
try
    add_line([model '/Plant_Process'], 'in_F1_Step_10/1', 'S6_Sum1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_F1_Step_10', 'S6_Sum1', ME.message);
end
try
    add_line([model '/Plant_Process'], 'in_F3_Value_11/1', 'S6_Sum1/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_F3_Value_11', 'S6_Sum1', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S6_Sum/1', 'S6_Sum2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S6_Sum', 'S6_Sum2', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Sum2/1', 'S6_Sum2/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum2', 'S6_Sum2', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Sum/1', 'S7_Gain/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum', 'S7_Gain', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Sum1/1', 'S7_Gain1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum1', 'S7_Gain1', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Saturation1/1', 'S7_Gain2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Saturation1', 'S7_Gain2', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_X2Int/1', 'S7_Gain3/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_X2Int', 'S7_Gain3', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Saturation1/1', 'S7_Gain4/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Saturation1', 'S7_Gain4', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Product2/1', 'S7_Gain5/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Product2', 'S7_Gain5', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Sum4/1', 'S7_Gain6/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum4', 'S7_Gain6', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Gain1/1', 'S7_P2Int/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain1', 'S7_P2Int', ME.message);
end
try
    add_line([model '/Plant_Process'], 'in_F1_Step_12/1', 'S7_Product/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_F1_Step_12', 'S7_Product', ME.message);
end
try
    add_line([model '/Plant_Process'], 'in_X1_Step_13/1', 'S7_Product/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_X1_Step_13', 'S7_Product', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S2_Saturation3/1', 'S7_Product1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation3', 'S7_Product1', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_X2Int/1', 'S7_Product1/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_X2Int', 'S7_Product1', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Sum5/1', 'S7_Product2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum5', 'S7_Product2', ME.message);
end
try
    add_line([model '/Plant_Process'], 'in_F1_Step_14/1', 'S7_Product2/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_F1_Step_14', 'S7_Product2', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Gain6/1', 'S7_Saturation/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain6', 'S7_Saturation', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_P2Int/1', 'S7_Saturation1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_P2Int', 'S7_Saturation1', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Saturation/1', 'S7_Saturation2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Saturation', 'S7_Saturation2', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Product/1', 'S7_Sum/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Product', 'S7_Sum', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Product1/1', 'S7_Sum/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Product1', 'S7_Sum', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Saturation2/1', 'S7_Sum1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Saturation2', 'S7_Sum1', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S2_Saturation5/1', 'S7_Sum1/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S2_Saturation5', 'S7_Sum1', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Gain3/1', 'S7_Sum2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain3', 'S7_Sum2', ME.message);
end
try
    add_line([model '/Plant_Process'], 'in_Constant_Value_15/1', 'S7_Sum2/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Constant_Value_15', 'S7_Sum2', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Gain2/1', 'S7_Sum2/3', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain2', 'S7_Sum2', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Gain4/1', 'S7_Sum3/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain4', 'S7_Sum3', ME.message);
end
try
    add_line([model '/Plant_Process'], 'in_Constant1_Value_i_16/1', 'S7_Sum3/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_Constant1_Value_i_16', 'S7_Sum3', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S6_Product/1', 'S7_Sum4/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S6_Product', 'S7_Sum4', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Gain5/1', 'S7_Sum4/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain5', 'S7_Sum4', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Sum2/1', 'S7_Sum5/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Sum2', 'S7_Sum5', ME.message);
end
try
    add_line([model '/Plant_Process'], 'in_T1_Value_17/1', 'S7_Sum5/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'in_T1_Value_17', 'S7_Sum5', ME.message);
end
try
    add_line([model '/Plant_Process'], 'S7_Gain/1', 'S7_X2Int/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'S7_Gain', 'S7_X2Int', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_F2_Value/1', 'out_F2_Value_1/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_F2_Value', 'out_F2_Value_1', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_P100_Value/1', 'out_P100_Value_2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_P100_Value', 'out_P100_Value_2', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_F200_Value/1', 'out_F200_Value_3/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_F200_Value', 'out_F200_Value_3', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_Constant_Value_c/1', 'out_Constant_Value_c_4/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_Constant_Value_c', 'out_Constant_Value_c_4', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_Constant1_Value_h/1', 'out_Constant1_Value_h_5/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_Constant1_Value_h', 'out_Constant1_Value_h_5', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_T200_Value/1', 'out_T200_Value_6/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_T200_Value', 'out_T200_Value_6', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_Constant2_Value/1', 'out_Constant2_Value_7/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_Constant2_Value', 'out_Constant2_Value_7', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_Constant1_Value/1', 'out_Constant1_Value_8/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_Constant1_Value', 'out_Constant1_Value_8', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_F3_Value/1', 'out_F3_Value_9/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_F3_Value', 'out_F3_Value_9', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_Constant_Value/1', 'out_Constant_Value_10/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_Constant_Value', 'out_Constant_Value_10', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_Constant1_Value_i/1', 'out_Constant1_Value_i_11/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_Constant1_Value_i', 'out_Constant1_Value_i_11', ME.message);
end
try
    add_line([model '/Inferred_Parameters'], 'inferred_Const_T1_Value/1', 'out_T1_Value_12/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'inferred_Const_T1_Value', 'out_T1_Value_12', ME.message);
end
% Connect top-level subsystem and interface signals.
try
    add_line(model, 'Plant_Process/1', 'L2/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Plant_Process', 'L2', ME.message);
end
try
    add_line(model, 'Plant_Process/2', 'Controller_Delay/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Plant_Process', 'Controller_Delay', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/1', 'Controller_Delay/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Controller_Delay', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/2', 'Plant_Process/1', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Plant_Process', ME.message);
end
try
    add_line(model, 'Controller_Delay/1', 'Plant_Process/2', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Controller_Delay', 'Plant_Process', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/3', 'Plant_Process/3', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Plant_Process', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/4', 'Plant_Process/4', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Plant_Process', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/5', 'Plant_Process/5', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Plant_Process', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/6', 'Plant_Process/6', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Plant_Process', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/7', 'Plant_Process/7', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Plant_Process', ME.message);
end
try
    add_line(model, 'Controller_Delay/2', 'Plant_Process/8', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Controller_Delay', 'Plant_Process', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/8', 'Plant_Process/9', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Plant_Process', ME.message);
end
try
    add_line(model, 'Controller_Delay/3', 'Plant_Process/10', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Controller_Delay', 'Plant_Process', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/9', 'Plant_Process/11', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Plant_Process', ME.message);
end
try
    add_line(model, 'Controller_Delay/4', 'Plant_Process/12', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Controller_Delay', 'Plant_Process', ME.message);
end
try
    add_line(model, 'Controller_Delay/5', 'Plant_Process/13', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Controller_Delay', 'Plant_Process', ME.message);
end
try
    add_line(model, 'Controller_Delay/6', 'Plant_Process/14', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Controller_Delay', 'Plant_Process', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/10', 'Plant_Process/15', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Plant_Process', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/11', 'Plant_Process/16', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Plant_Process', ME.message);
end
try
    add_line(model, 'Inferred_Parameters/12', 'Plant_Process/17', 'autorouting', 'on');
catch ME
    warning('Could not add line %s -> %s: %s', 'Inferred_Parameters', 'Plant_Process', ME.message);
end

% Validate expected top-level block and signal-line counts.
fprintf('[validation] Checking top-level block and signal-line counts.\n');
actualBlockCount = numel(find_system(model, 'Type', 'Block'));
actualLineCount = numel(find_system(model, 'FindAll', 'on', 'Type', 'line'));
if actualBlockCount ~= expectedBlockCount
    warning('Expected %d blocks, but found %d.', expectedBlockCount, actualBlockCount);
end
if actualLineCount ~= expectedLineCount
    warning('Expected %d signal lines, but found %d.', expectedLineCount, actualLineCount);
end

% Add reconstruction notes and unmapped-code annotations.
try
    ann = Simulink.Annotation(model, 'Layout strategy: Simple subsystem preferred. A compact top-level diagram uses a few coarse subsystems for controller, plant/process, and inferred parameter helpers.');
    ann.Position = [30 75 520 110];
catch ME
    warning('Could not add annotation: %s', ME.message);
end
try
    ann = Simulink.Annotation(model, 'This model is inferred from generated C code. Simulink Coder output is not lossless; names, hierarchy, masks, sample times, solver settings, and annotations may differ from the original model.');
    ann.Position = [30 120 520 155];
catch ME
    warning('Could not add annotation: %s', ME.message);
end

fprintf('[save] Saving model to %s.slx.\n', model);
save_system(model);
fprintf('[summary] Blocks: %d; signal lines: %d; model: %s; layout: %s.\n', actualBlockCount, actualLineCount, model, layoutStrategy);
